/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/hello.cob */
/* Generated at           Sep 19 2026 10:45:38 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -x -A -O0 -gdwarf-4 -o C:/work/cobol/build/hello-dw4/hello.exe -g -fdump=ALL --save-temps -t C:/work/cobol/build/hello-dw4/hello-dw4.lst -ftsymbols C:/work/cobol/examples/hello.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_5 =	{0x11,   4,   0, 0x0820, NULL};
static const cob_field_attr a_6 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x12,   9,   2, 0x0001, NULL};
static const cob_field_attr a_8 =	{0x10,   7,   2, 0x0001, NULL};
static const cob_field_attr a_9 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_10 =	{0x10,   9,   0, 0x0007, NULL};
static const cob_field_attr a_11 =	{0x11,   9,   0, 0x0821, NULL};
static const cob_field_attr a_12 =	{0x10,   7,   2, 0x0007, NULL};
static const cob_field_attr a_13 =	{0x10,   9,   0, 0x1000, NULL};
static const cob_field_attr a_14 =	{0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_15 =	{0x10,   6,   5, 0x1000, NULL};
static const cob_field_attr a_16 =	{0x14,  34,  17, 0x0201, NULL};
static const cob_field_attr a_17 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_18 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_19 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_20 =	{0x10,   8,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {3, (cob_u8_ptr)"100", &a_1};
static const cob_field c_2	= {3, (cob_u8_ptr)"ABC", &a_2};
static const cob_field c_3	= {1, (cob_u8_ptr)"1", &a_4};
static const cob_field c_4	= {26, (cob_u8_ptr)"COBOL_DEBUG_MARKER: total=", &a_2};
static const cob_field c_5	= {5, (cob_u8_ptr)"name=", &a_2};
static const cob_field c_6	= {4, (cob_u8_ptr)" id=", &a_2};
static const cob_field c_7	= {10, (cob_u8_ptr)"-123456789", &a_10};
static const cob_field c_8	= {8, (cob_u8_ptr)"-1234567", &a_12};
static const cob_field c_9	= {9, (cob_u8_ptr)"987654321", &a_13};
static const cob_field c_10	= {6, (cob_u8_ptr)"314159", &a_15};
static const cob_field c_11	= {1, (cob_u8_ptr)"0", &a_4};
static const cob_field c_12	= {1, (cob_u8_ptr)"A", &a_2};
static const cob_field c_13	= {1, (cob_u8_ptr)"C", &a_2};
static const cob_field c_14	= {1, (cob_u8_ptr)"X", &a_2};


/* Strings */
static const char st_1[]	= "0000-MAIN";
static const char st_2[]	= "1000-INIT";
static const char st_3[]	= "2000-COMPUTE";
static const char st_4[]	= "3000-REPORT";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"C:/work/cobol/examples/hello.cob"};

#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < val; ++n, ++p) {
		if (*p > '0' && *p <= '9')
			break;
	}
	for (n = 0; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}


static COB_INLINE COB_A_INLINE int
cob_cmpswp_u16 (const void *p, const cob_s64_t n)
{
	unsigned short	val;
	if (unlikely(n < 0)) {
		return 1;
	}
	val = COB_BSWAP_16 (*(unsigned short *)p);
	return (val < n) ? -1 : (val > n);
}


static COB_INLINE COB_A_INLINE void
cob_addswp_u16 (void *p, const int val)
{
	unsigned short	n;
	n = COB_BSWAP_16 (*(unsigned short *)p);
	n += val;
	*(unsigned short *)p = COB_BSWAP_16(n);
}


/* Decimal constants */
static	cob_decimal	kc_1;
static	cob_decimal	*dc_1 = NULL;

