/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/copybook/main.cob */
/* Generated at           Sep 19 2026 10:45:40 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -x -I C:\work\cobol\examples\copybook -A -O0 -gdwarf-4 -o C:/work/cobol/build/copybook/cpymain.exe -g -fdump=ALL --save-temps -t C:/work/cobol/build/copybook/copybook.lst -ftsymbols C:/work/cobol/examples/copybook/main.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   7,   2, 0x0001, NULL};
static const cob_field_attr a_3 =	{0x12,   4,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_5 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {26, (cob_u8_ptr)"COBOL_DEBUG_MARKER: price=", &a_1};
static const cob_field c_2	= {21, (cob_u8_ptr)"in copybook paragraph", &a_1};


/* Strings */
static const char st_1[]	= "0000-MAIN";
static const char st_2[]	= "9000-FROM-COPYBOOK";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"C:/work/cobol/examples/copybook/main.cob"
		,"C:\\work\\cobol\\examples\\copybook\\procpara.cpy"};

#define cob_nop	if (!module) cob_nop

