/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 10:45:40 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -x --debug -A -O0 -gdwarf-4 -o C:/work/cobol/build/rterror/rterror.exe -g -fdump=ALL --save-temps -t C:/work/cobol/build/rterror/rterror.lst -ftsymbols C:/work/cobol/examples/rterror.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   4,   0, 0x0820, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_7 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"5", &a_1};
static const cob_field c_2	= {15, (cob_u8_ptr)"about to index ", &a_3};
static const cob_field c_3	= {24, (cob_u8_ptr)"COBOL_DEBUG_MARKER: sum=", &a_3};
static const cob_field c_4	= {1, (cob_u8_ptr)"0", &a_1};


/* Strings */
static const char st_1[]	= "0000-MAIN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"C:/work/cobol/examples/rterror.cob"};

static void COB_INLINE COB_A_INLINE
cob_check_subscript_inline (const int i, const int max,
			const char* name, const int odo_item)
{
	if (i < 1 || i > max) {
		cob_check_subscript (i, max, name, odo_item);
	}
}
#define cob_check_subscript	cob_check_subscript_inline


#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < val; ++n, ++p) {
		if (*p > '0' && *p <= '9')
			break;
	}
	for (n = 0; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

