/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/dyn/mod1.cob */
/* Generated at           Sep 19 2026 14:46:11 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -m -A -O0 -gdwarf-4 -o /work/cobol/build/dyn-mod1/MOD1.so -g -fdump=ALL --save-temps -t /work/cobol/build/dyn-mod1/dyn-mod1.lst -ftsymbols /work/cobol/examples/dyn/mod1.cob */

/* Program local variables for 'MOD1' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_8;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {4, NULL, &a_1};	/* LK-VALUE */

/* End of fields */

