/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 14:46:07 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x --debug -A -O0 -gdwarf-4 -o /work/cobol/build/rterror/rterror -g -fdump=ALL --save-temps -t /work/cobol/build/rterror/rterror.lst -ftsymbols /work/cobol/examples/rterror.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/rterror.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:07"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144607

/* Global variables */
#include "rterror.c.h"

/* Function prototypes */

static int		RTERROR ();
static int		RTERROR_ (const int);
static void		RTERROR_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (RTERROR ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'RTERROR' */

/* ENTRY 'RTERROR' */

static int
RTERROR ()
{
  return RTERROR_ (0);
}

static int
RTERROR_ (const int entry)
{
  /* Program local variables */
  #include "rterror.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "RTERROR";
  module->frame_ptr->module_stmt = 0x0010000A;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     RTERROR                 : /work/cobol/examples/rterror.cob */
  l_2:;
#line 10 "/work/cobol/examples/rterror.cob"
  ENTRY_RTERROR:	module->statement = STMT_ENTRY;
#line 109 "rterror.c"
  module->module_stmt = 0x0010000A;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 10        : Paragraph 0000-MAIN               : /work/cobol/examples/rterror.cob */
#line 10 "/work/cobol/examples/rterror.cob"
  PARAGRAPH_0000__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 117 "rterror.c"
  module->paragraph_name = st_1;

  /* Line: 11        : MOVE               : /work/cobol/examples/rterror.cob */
#line 11 "/work/cobol/examples/rterror.cob"
  module->statement = STMT_MOVE;
#line 123 "rterror.c"
  module->module_stmt = 0x0010000B;
  cob_move ((cob_field *)&c_1, &f_19);

  /* Line: 12        : DISPLAY            : /work/cobol/examples/rterror.cob */
#line 12 "/work/cobol/examples/rterror.cob"
  module->statement = STMT_DISPLAY;
#line 130 "rterror.c"
  module->module_stmt = 0x0010000C;
  cob_display (0, 1, 2, &c_2, &f_19);

  /* Line: 13        : ADD                : /work/cobol/examples/rterror.cob */
#line 13 "/work/cobol/examples/rterror.cob"
  module->statement = STMT_ADD;
#line 137 "rterror.c"
  module->module_stmt = 0x0010000D;
  cob_check_numeric (
  (cob_check_subscript (((unsigned short)COB_BSWAP_16(*(short *)(b_19))), 3, "WS-CELL", 0),
  COB_SET_FLD (f0, 3, b_17 + 3LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_19)))) - 1), &a_4) ), "WS-CELL");
  cob_check_numeric (&f_20, "WS-SUM");
  cob_add_int (&f_20, cob_get_numdisp (b_17 + 3LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_19)))) - 1), 3), 0);

  /* Line: 14        : DISPLAY            : /work/cobol/examples/rterror.cob */
#line 14 "/work/cobol/examples/rterror.cob"
  module->statement = STMT_DISPLAY;
#line 148 "rterror.c"
  module->module_stmt = 0x0010000E;
  cob_display (0, 1, 2, &c_3, &f_20);

  /* Line: 15        : STOP RUN           : /work/cobol/examples/rterror.cob */
#line 15 "/work/cobol/examples/rterror.cob"
  module->statement = STMT_STOP_RUN;
#line 155 "rterror.c"
  module->module_stmt = 0x0010000F;
  cob_stop_run (b_2);

  /* Line: 16        : last source line                  :/work/cobol/examples/rterror.cob */
#line 16 "/work/cobol/examples/rterror.cob"
  module->module_stmt = 0x00100010;
#line 162 "rterror.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  RTERROR_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize WS-CELL: init first record */
  {
    /* initialize field WS-CELL */
#line 6 "/work/cobol/examples/rterror.cob"
    cob_nop ();
#line 218 "rterror.c"
    memcpy (b_17, "007", 3);
    /* initialize WS-CELL: copy initialized record to later occurrences */
    {
      cob_u8_ptr b_ptr = b_17;
      memcpy (b_ptr +      3, b_ptr,      3);	/* WS-CELL:     2 thru 2 */
      memcpy (b_ptr +      6, b_ptr,      3);	/* WS-CELL:     3 thru 3 */
    }
  }

  /* initialize field WS-IDX */
#line 7 "/work/cobol/examples/rterror.cob"
  cob_nop ();
#line 231 "rterror.c"
  cob_move ((cob_field *)&c_4, &f_19);

  /* initialize field WS-SUM */
#line 8 "/work/cobol/examples/rterror.cob"
  cob_nop ();
#line 237 "rterror.c"
  memset (b_20, 48, 6);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump WORKING-STORAGE */
  cob_dump_output ("WORKING-STORAGE");
  cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_6), 0, 0);
  cob_dump_field_ext ( 1, "WS-TABLE", COB_SET_FLD (f0, 9, b_17, &a_7), 0, 0);
  {
    int i_1;
    int max_1 = 3;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-CELL", &f_18, 0, 1, i_1, 3UL); /* OCCURS 1 3 */
    }
  }
  cob_dump_field_ext ( 1, "WS-IDX", &f_19, 0, 0);
  cob_dump_field_ext ( 1, "WS-SUM", &f_20, 0, 0);

  cob_dump_output ("END OF DUMP - RTERROR");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'RTERROR' */

/* Initialize module structure for RTERROR */
static void RTERROR_module_init (cob_module *module)
{
  module->module_name = "RTERROR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())RTERROR;
  module->module_cancel.funcptr = (void *(*)())RTERROR_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

