/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 14:46:07 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x --debug -A -O0 -gdwarf-4 -o /work/cobol/build/rterror/rterror -g -fdump=ALL --save-temps -t /work/cobol/build/rterror/rterror.lst -ftsymbols /work/cobol/examples/rterror.cob */

/* Program local variables for 'RTERROR' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[9] __attribute__((aligned));	/* WS-TABLE */
static cob_u8_t	b_19[2] __attribute__((aligned));	/* WS-IDX */
static cob_u8_t	b_20[6] __attribute__((aligned));	/* WS-SUM */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {3, b_17, &a_4};	/* WS-CELL */
static cob_field f_19	= {2, b_19, &a_2};	/* WS-IDX */
static cob_field f_20	= {6, b_20, &a_5};	/* WS-SUM */

/* End of fields */

