/**
 * The published @debugmcp/mcp-debugger package is also a pi coding-agent
 * package (issue #714): its manifest points pi at a shipped copy of the agent
 * skill and at an extension that registers the server with pi's built-in MCP
 * support (issue #841). These tests pin that the manifest references only paths
 * that ship, that the extension registers the bundled CLI over stdio (and does
 * nothing on a pi without built-in MCP), and that the shipped skill is a
 * byte-identical copy of skills/debugging (generated by the bundle build).
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const packageDir = path.join(root, 'packages', 'mcp-debugger');
const sourceSkill = path.join(root, 'skills', 'debugging');
const shippedSkill = path.join(packageDir, 'skills', 'debugging');

interface PackageManifest {
  files: string[];
  pi?: { skills?: string[]; mcp?: string[]; extensions?: string[] };
}

const manifest = JSON.parse(
  readFileSync(path.join(packageDir, 'package.json'), 'utf8')
) as PackageManifest;

interface PiExtensionModule {
  default: (pi: { registerMcpServer?: (name: string, config: Record<string, unknown>) => void }) => void;
  nodeCommand: (execPath: string) => string;
}

/** The shipped extension, loaded the way pi loads it: as an ES module from the package directory. */
async function loadExtension(): Promise<PiExtensionModule> {
  return (await import(pathToFileURL(path.join(packageDir, 'extensions', 'mcp-debugger.js')).href)) as PiExtensionModule;
}

function walk(dir: string, base = dir): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => {
      const full = path.join(dir, entry.name);
      return entry.isDirectory()
        ? walk(full, base)
        : [path.relative(base, full).replace(/\\/g, '/')];
    })
    .sort();
}

describe('published package pi manifest (issue #714)', () => {
  it('declares the skill directory and the extension, both covered by "files"', () => {
    expect(manifest.pi).toEqual({ extensions: ['./extensions/mcp-debugger.js'], skills: ['./skills'] });
    for (const entry of [...(manifest.pi?.skills ?? []), ...(manifest.pi?.extensions ?? [])]) {
      const top = entry.replace(/^\.\//, '').split('/')[0];
      expect(manifest.files, `${top} is not in package.json "files"`).toContain(top);
    }
    for (const entry of manifest.pi?.extensions ?? []) {
      expect(existsSync(path.join(packageDir, entry)), `${entry} is missing`).toBe(true);
    }
  });

  it('the extension registers the bundled CLI over stdio with the built-in MCP support', async () => {
    const extension = await loadExtension();
    const registered: Array<[string, Record<string, unknown>]> = [];
    extension.default({
      registerMcpServer: (name: string, config: Record<string, unknown>) => registered.push([name, config]),
    });

    expect(registered).toHaveLength(1);
    const [name, config] = registered[0];
    expect(name).toBe('mcp-debugger');
    expect(config.args).toEqual([path.join(packageDir, 'dist', 'cli.mjs'), 'stdio']);
    expect(config.command).toBe(process.execPath);
    expect(config.exposure).toBe('deferred');
    expect(config.timeout).toBe(180);
    // pi shows at most 250 characters of a description in the system prompt's mcp_servers section.
    expect(String(config.description).length).toBeLessThanOrEqual(250);
  });

  it('the extension runs the CLI with node from PATH when the host process is not a node binary', async () => {
    const extension = await loadExtension();
    expect(extension.nodeCommand('/usr/local/bin/node')).toBe('/usr/local/bin/node');
    expect(extension.nodeCommand('C:\\Program Files\\nodejs\\node.exe')).toBe('C:\\Program Files\\nodejs\\node.exe');
    expect(extension.nodeCommand('/opt/pi/pi')).toBe('node');
  });

  it('the extension does nothing on a pi without built-in MCP support (pi < 0.99)', async () => {
    const extension = await loadExtension();
    expect(() => extension.default({})).not.toThrow();
  });

  it('ships a byte-identical copy of skills/debugging', () => {
    expect(
      existsSync(shippedSkill),
      `Generated skill copy missing at ${shippedSkill}; run "npm run build" first`
    ).toBe(true);
    const files = walk(sourceSkill);
    expect(files).toContain('SKILL.md');
    expect(walk(shippedSkill)).toEqual(files);
    for (const file of files) {
      const shipped = readFileSync(path.join(shippedSkill, file));
      const source = readFileSync(path.join(sourceSkill, file));
      expect(shipped.equals(source), `${file} differs from skills/debugging`).toBe(true);
    }
    expect(readFileSync(path.join(shippedSkill, 'SKILL.md'), 'utf8')).toMatch(
      /^---\r?\nname: mcp-debugger\r?\n/
    );
  });
});
