/**
 * The published @debugmcp/mcp-debugger package is also a pi coding-agent
 * package (issue #714): its manifest points pi at a shipped copy of the agent
 * skill and points pi-mcp-adapter at a server entry. These tests pin that the
 * manifest references only paths that ship, that the server entry is the same
 * stdio recipe every other client uses, and that the shipped skill is a
 * byte-identical copy of skills/debugging (generated by the bundle build).
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const packageDir = path.join(root, 'packages', 'mcp-debugger');
const sourceSkill = path.join(root, 'skills', 'debugging');
const shippedSkill = path.join(packageDir, 'skills', 'debugging');

interface PackageManifest {
  files: string[];
  pi?: { skills?: string[]; mcp?: string[]; extensions?: string[] };
}

const manifest = JSON.parse(
  readFileSync(path.join(packageDir, 'package.json'), 'utf8')
) as PackageManifest;

function walk(dir: string, base = dir): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => {
      const full = path.join(dir, entry.name);
      return entry.isDirectory()
        ? walk(full, base)
        : [path.relative(base, full).replace(/\\/g, '/')];
    })
    .sort();
}

describe('published package pi manifest (issue #714)', () => {
  it('declares the skill directory and the adapter config, both covered by "files"', () => {
    expect(manifest.pi).toEqual({ skills: ['./skills'], mcp: ['./pi.mcp.json'] });
    for (const entry of [...(manifest.pi?.skills ?? []), ...(manifest.pi?.mcp ?? [])]) {
      const top = entry.replace(/^\.\//, '').split('/')[0];
      expect(manifest.files, `${top} is not in package.json "files"`).toContain(top);
    }
    for (const entry of manifest.pi?.mcp ?? []) {
      expect(existsSync(path.join(packageDir, entry)), `${entry} is missing`).toBe(true);
    }
  });

  it('contributes the same stdio server entry every client recipe uses', () => {
    const config = JSON.parse(readFileSync(path.join(packageDir, 'pi.mcp.json'), 'utf8')) as {
      mcpServers: Record<string, unknown>;
    };
    expect(Object.keys(config.mcpServers)).toEqual(['mcp-debugger']);
    expect(config.mcpServers['mcp-debugger']).toEqual({
      command: 'npx',
      args: ['-y', '@debugmcp/mcp-debugger', 'stdio'],
    });
  });

  it('ships a byte-identical copy of skills/debugging', () => {
    expect(
      existsSync(shippedSkill),
      `Generated skill copy missing at ${shippedSkill}; run "npm run build" first`
    ).toBe(true);
    const files = walk(sourceSkill);
    expect(files).toContain('SKILL.md');
    expect(walk(shippedSkill)).toEqual(files);
    for (const file of files) {
      const shipped = readFileSync(path.join(shippedSkill, file));
      const source = readFileSync(path.join(sourceSkill, file));
      expect(shipped.equals(source), `${file} differs from skills/debugging`).toBe(true);
    }
    expect(readFileSync(path.join(shippedSkill, 'SKILL.md'), 'utf8')).toMatch(
      /^---\r?\nname: mcp-debugger\r?\n/
    );
  });
});
