/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/dyn/mod1.cob */
/* Generated at           Sep 19 2026 10:45:41 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -m -A -O0 -gdwarf-4 -o C:/work/cobol/build/dyn-mod1/MOD1.dll -g -fdump=ALL --save-temps -t C:/work/cobol/build/dyn-mod1/dyn-mod1.lst -ftsymbols C:/work/cobol/examples/dyn/mod1.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:/work/cobol/examples/dyn/mod1.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 10:45:41"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		104541

/* Global variables */
#include "mod1.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		MOD1 (cob_u8_t *);
static int		MOD1_ (const int, cob_u8_t *);
static void		MOD1_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'MOD1' */

/* ENTRY 'MOD1' */

int
MOD1 (cob_u8_t *b_17)
{
  cob_u8_t *cob_parm_17 = NULL;	/* linkage for LK-VALUE */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 1;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_17 = b_17;
  }

  return MOD1_ (0, cob_parm_17);
}

static int
MOD1_ (const int entry, cob_u8_t *b_17)
{
  /* Program local variables */
  #include "mod1.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_17 = b_17;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "MOD1";
  module->frame_ptr->module_stmt = 0x00100007;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     MOD1                    : C:/work/cobol/examples/dyn/mod1.cob */
  l_2:;
#line 7 "C:/work/cobol/examples/dyn/mod1.cob"
  ENTRY_MOD1:	module->statement = STMT_ENTRY;
#line 119 "mod1.c"
  module->module_stmt = 0x00100007;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 7         : Paragraph 0000-MOD-MAIN           : C:/work/cobol/examples/dyn/mod1.cob */
#line 7 "C:/work/cobol/examples/dyn/mod1.cob"
  PARAGRAPH_0000__MOD__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 127 "mod1.c"
  module->paragraph_name = st_1;

  /* Line: 8         : ADD                : C:/work/cobol/examples/dyn/mod1.cob */
#line 8 "C:/work/cobol/examples/dyn/mod1.cob"
  module->statement = STMT_ADD;
#line 133 "mod1.c"
  module->module_stmt = 0x00100008;
  cob_add (COB_SET_DATA (f_17, b_17), (cob_field *)&c_1, 4);

  /* Line: 9         : GOBACK             : C:/work/cobol/examples/dyn/mod1.cob */
#line 9 "C:/work/cobol/examples/dyn/mod1.cob"
  module->statement = STMT_GOBACK;
#line 140 "mod1.c"
  module->module_stmt = 0x00100009;
  goto exit_program;

  /* Line: 10        : last source line                  :C:/work/cobol/examples/dyn/mod1.cob */
#line 10 "C:/work/cobol/examples/dyn/mod1.cob"
  module->module_stmt = 0x0010000A;
#line 147 "mod1.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  MOD1_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output ("WORKING-STORAGE");
    cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_3), 0, 0);


    /* Dump LINKAGE SECTION */
    b_17 = last_b_17;
    cob_dump_output ("LINKAGE");
    /* Check LINKAGE address for LK-VALUE */
    if (b_17 == NULL)
    {
      cob_dump_field_ext ( 1, "LK-VALUE", COB_SET_FLD (f0, 4, NULL, &a_1), 0, 0);
    }
    else
    {
      cob_dump_field_ext ( 1, "LK-VALUE", COB_SET_FLD (f0, 4, b_17, &a_1), 0, 0);
    }

  }
  cob_dump_output ("END OF DUMP - MOD1");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'MOD1' */

/* Initialize module structure for MOD1 */
static void MOD1_module_init (cob_module *module)
{
  module->module_name = "MOD1";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())MOD1;
  module->module_cancel.funcptr = (void *(*)())MOD1_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

