/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/hello.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/hello-dw4/hello -g -fdump=ALL --save-temps -t /work/cobol/build/hello-dw4/hello-dw4.lst -ftsymbols /work/cobol/examples/hello.cob */

/* Program local variables for 'HELLO' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[12] __attribute__((aligned));	/* WS-ALPHA */
static cob_u8_t	b_9[5] __attribute__((aligned));	/* WS-U */
static cob_u8_t	b_10[7] __attribute__((aligned));	/* WS-SCALED */
static cob_u8_t	b_11[4] __attribute__((aligned));	/* WS-BINARY */
static cob_u8_t	b_12[5] __attribute__((aligned));	/* WS-PACKED */
static cob_u8_t	b_13[4] __attribute__((aligned));	/* WS-COMP5 */
static cob_u8_t	b_14[8] __attribute__((aligned));	/* WS-DOUBLE */
static cob_u8_t	b_15[25] __attribute__((aligned));	/* WS-GROUP */
static cob_u8_t	b_21[20] __attribute__((aligned));	/* WS-TABLE */
static cob_u8_t	b_24[1] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_25[9] __attribute__((aligned));	/* WS-ODO */
static cob_u8_t	b_27[8] __attribute__((aligned));	/* WS-RAW */
static cob_u8_t	b_29[5] __attribute__((aligned));	/* WS-TOTAL */
static cob_u8_t	b_30[2] __attribute__((aligned));	/* WS-IDX */

/* End of local data storage */


/* Fields (local) */
static cob_field f_10	= {7, b_10, &a_8};	/* WS-SCALED */
static cob_field f_16	= {4, b_15, &a_6};	/* WS-ID */
static cob_field f_17	= {20, b_15 + 4, &a_9};	/* WS-NAME */
static cob_field f_23	= {4, b_21, &a_6};	/* WS-AMOUNT */
static cob_field f_24	= {1, b_24, &a_18};	/* WS-COUNT */
static cob_field f_29	= {5, b_29, &a_7};	/* WS-TOTAL */
static cob_field f_30	= {2, b_30, &a_5};	/* WS-IDX */

/* End of fields */

