/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/dyn/mod1.cob */
/* Generated at           Sep 19 2026 14:46:07 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -m -A -O0 -gdwarf-4 -o /work/cobol/build/dyn-mod1/MOD1.so -g -fdump=ALL --save-temps -t /work/cobol/build/dyn-mod1/dyn-mod1.lst -ftsymbols /work/cobol/examples/dyn/mod1.cob */

/* Program local variables for 'MOD1' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_17;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, NULL, &a_1};	/* LK-VALUE */

/* End of fields */

