/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/copybook/main.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -I /work/cobol/examples/copybook -A -O0 -gdwarf-4 -o /work/cobol/build/copybook/cpymain -g -fdump=ALL --save-temps -t /work/cobol/build/copybook/copybook.lst -ftsymbols /work/cobol/examples/copybook/main.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/copybook/main.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:06"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144606

/* Global variables */
#include "main.c.h"

/* Function prototypes */

static int		CPYMAIN ();
static int		CPYMAIN_ (const int);
static void		CPYMAIN_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CPYMAIN ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CPYMAIN' */

/* ENTRY 'CPYMAIN' */

static int
CPYMAIN ()
{
  return CPYMAIN_ (0);
}

static int
CPYMAIN_ (const int entry)
{
  /* Program local variables */
  #include "main.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "CPYMAIN";
  module->frame_ptr->module_stmt = 0x00100008;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 8         : Entry     CPYMAIN                 : /work/cobol/examples/copybook/main.cob */
  l_2:;
#line 8 "/work/cobol/examples/copybook/main.cob"
  ENTRY_CPYMAIN:	module->statement = STMT_ENTRY;
#line 113 "main.c"
  module->module_stmt = 0x00100008;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 8         : Paragraph 0000-MAIN               : /work/cobol/examples/copybook/main.cob */
#line 8 "/work/cobol/examples/copybook/main.cob"
  PARAGRAPH_0000__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 121 "main.c"
  module->paragraph_name = st_1;

  /* Line: 9         : PERFORM            : /work/cobol/examples/copybook/main.cob */
#line 9 "/work/cobol/examples/copybook/main.cob"
  module->statement = STMT_PERFORM;
#line 127 "main.c"
  module->module_stmt = 0x00100009;
  /* PERFORM 9000-FROM-COPYBOOK */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_6;
  goto l_5;
  l_6:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 10        : MOVE               : /work/cobol/examples/copybook/main.cob */
#line 10 "/work/cobol/examples/copybook/main.cob"
  module->statement = STMT_MOVE;
#line 150 "main.c"
  module->module_stmt = 0x0010000A;
  *(b_21) = 89;

  /* Line: 11        : DISPLAY            : /work/cobol/examples/copybook/main.cob */
#line 11 "/work/cobol/examples/copybook/main.cob"
  module->statement = STMT_DISPLAY;
#line 157 "main.c"
  module->module_stmt = 0x0010000B;
  cob_display (0, 1, 2, &c_1, &f_20);

  /* Line: 12        : STOP RUN           : /work/cobol/examples/copybook/main.cob */
#line 12 "/work/cobol/examples/copybook/main.cob"
  module->statement = STMT_STOP_RUN;
#line 164 "main.c"
  module->module_stmt = 0x0010000C;
  cob_stop_run (b_2);

  /* Line: 1         : Paragraph 9000-FROM-COPYBOOK      : /work/cobol/examples/copybook/procpara.cpy */
  l_5:;
#line 1 "/work/cobol/examples/copybook/procpara.cpy"
  PARAGRAPH_9000__FROM__COPYBOOK_l_5:	module->statement = STMT_ENTRY;
#line 172 "main.c"
  module->module_stmt = 0x00200001;
  module->paragraph_name = st_2;

  /* Line: 2         : COMPUTE            : /work/cobol/examples/copybook/procpara.cpy */
#line 2 "/work/cobol/examples/copybook/procpara.cpy"
  module->statement = STMT_COMPUTE;
#line 179 "main.c"
  module->module_stmt = 0x00200002;
  cob_decimal_set_field (d_0, &f_20);
  cob_decimal_set_field (d_1, &f_19);
  cob_decimal_mul (d_0, d_1);
  cob_decimal_get_field (d_0, &f_20, 0);

  /* Line: 3         : DISPLAY            : /work/cobol/examples/copybook/procpara.cpy */
#line 3 "/work/cobol/examples/copybook/procpara.cpy"
  module->statement = STMT_DISPLAY;
#line 189 "main.c"
  module->module_stmt = 0x00200003;
  cob_display (0, 1, 1, &c_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 14        : last source line                  :/work/cobol/examples/copybook/main.cob */
#line 14 "/work/cobol/examples/copybook/main.cob"
  module->module_stmt = 0x0010000E;
#line 200 "main.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CPYMAIN_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field CP-CODE */
#line 2 "/work/cobol/examples/copybook/wsrec.cpy"
  cob_nop ();
#line 254 "main.c"
  memcpy (b_17, "CPY", 3);
  /* initialize field CP-QTY */
#line 3 "/work/cobol/examples/copybook/wsrec.cpy"
  cob_nop ();
#line 259 "main.c"
  cob_set_packed_int (&f_19, 12);
  /* initialize field CP-PRICE */
#line 4 "/work/cobol/examples/copybook/wsrec.cpy"
  cob_nop ();
#line 264 "main.c"
  memcpy (b_17 + 6, "0001999", 7);

  /* initialize field WS-DONE */
#line 6 "/work/cobol/examples/copybook/main.cob"
  cob_nop ();
#line 270 "main.c"
  *(cob_u8_ptr)(b_21) = (unsigned char)'N';


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output ("WORKING-STORAGE");
    cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_4), 0, 0);
    cob_dump_field_ext ( 1, "CP-REC", COB_SET_FLD (f0, 13, b_17, &a_5), 0, 0);
    cob_dump_field_ext ( 5, "CP-CODE", COB_SET_FLD (f0, 3, b_17, &a_6), 0, 0);
    cob_dump_field_ext ( 5, "CP-QTY", &f_19, 0, 0);
    cob_dump_field_ext ( 5, "CP-PRICE", &f_20, 0, 0);
    cob_dump_field_ext ( 1, "WS-DONE", &f_21, 0, 0);

  }
  cob_dump_output ("END OF DUMP - CPYMAIN");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CPYMAIN' */

/* Initialize module structure for CPYMAIN */
static void CPYMAIN_module_init (cob_module *module)
{
  module->module_name = "CPYMAIN";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CPYMAIN;
  module->module_cancel.funcptr = (void *(*)())CPYMAIN_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

