/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/copybook/main.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -I /work/cobol/examples/copybook -A -O0 -gdwarf-4 -o /work/cobol/build/copybook/cpymain -g -fdump=ALL --save-temps -t /work/cobol/build/copybook/copybook.lst -ftsymbols /work/cobol/examples/copybook/main.cob */

/* Program local variables for 'CPYMAIN' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[13] __attribute__((aligned));	/* CP-REC */
static cob_u8_t	b_21[1] __attribute__((aligned));	/* WS-DONE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_19	= {3, b_17 + 3, &a_3};	/* CP-QTY */
static cob_field f_20	= {7, b_17 + 6, &a_2};	/* CP-PRICE */
static cob_field f_21	= {1, b_21, &a_6};	/* WS-DONE */

/* End of fields */

