/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/calls/sub.cob */
/* Generated at           Sep 19 2026 10:45:39 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -x -A -O0 -gdwarf-4 -o C:/work/cobol/build/calls/calls.exe -g -fdump=ALL --save-temps -t C:/work/cobol/build/calls/calls.lst -ftsymbols C:/work/cobol/examples/calls/main.cob C:/work/cobol/examples/calls/sub.cob */

/* Program local variables for 'CALLSUB' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;
cob_decimal	*d_1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */

/* Last USING parameters for possible later lookup */
static unsigned char	*last_b_19;

/* LOCAL storage pointer */
unsigned char		*cob_local_ptr = NULL;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, NULL, &a_2};	/* LS-WORK */

/* End of fields */

