/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/calls/sub.cob */
/* Generated at           Sep 19 2026 10:45:39 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -x -A -O0 -gdwarf-4 -o C:/work/cobol/build/calls/calls.exe -g -fdump=ALL --save-temps -t C:/work/cobol/build/calls/calls.lst -ftsymbols C:/work/cobol/examples/calls/main.cob C:/work/cobol/examples/calls/sub.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:/work/cobol/examples/calls/sub.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 10:45:39"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		104539

/* Global variables */
#include "sub.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		CALLSUB (cob_u8_t *);
static int		CALLSUB_ (const int, cob_u8_t *);
static void		CALLSUB_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'CALLSUB' */

/* ENTRY 'CALLSUB' */

int
CALLSUB (cob_u8_t *b_19)
{
  cob_u8_t *cob_parm_19 = NULL;	/* linkage for LK-ARG-REC */

  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 1;
  }

  /* Set the parameter list */
  if (cob_call_params > 0) {
    cob_parm_19 = b_19;
  }

  return CALLSUB_ (0, cob_parm_19);
}

static int
CALLSUB_ (const int entry, cob_u8_t *b_19)
{
  /* Program local variables */
  #include "sub.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Allocate LOCAL storage */
  cob_local_ptr = cob_malloc (32U);

  /* Initialize LOCAL storage */
  /* initialize field LS-WORK */
#line 5 "C:/work/cobol/examples/calls/sub.cob"
  cob_nop ();
#line 103 "sub.c"
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_17, cob_local_ptr));

  /* initialize field LS-TAG */
#line 6 "C:/work/cobol/examples/calls/sub.cob"
  cob_nop ();
#line 109 "sub.c"
  memcpy (cob_local_ptr + 16, "LOCAL ", 6);


  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d_0, &d_1);

  /* Increment module active */
  module->module_active++;

  /* Store last parameters for possible later lookup */
  last_b_19 = b_19;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "CALLSUB";
  module->frame_ptr->module_stmt = 0x0010000E;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     CALLSUB                 : C:/work/cobol/examples/calls/sub.cob */
  l_2:;
#line 14 "C:/work/cobol/examples/calls/sub.cob"
  ENTRY_CALLSUB:	module->statement = STMT_ENTRY;
#line 140 "sub.c"
  module->module_stmt = 0x0010000E;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 14        : Paragraph 0000-SUB-MAIN           : C:/work/cobol/examples/calls/sub.cob */
#line 14 "C:/work/cobol/examples/calls/sub.cob"
  PARAGRAPH_0000__SUB__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 148 "sub.c"
  module->paragraph_name = st_1;

  /* Line: 15        : ADD                : C:/work/cobol/examples/calls/sub.cob */
#line 15 "C:/work/cobol/examples/calls/sub.cob"
  module->statement = STMT_ADD;
#line 154 "sub.c"
  module->module_stmt = 0x0010000F;
  cob_decimal_set_llint (d_0, ((int)COB_BSWAP_32(*(int *)(b_19))));
  cob_decimal_set_llint (d_1, ((int)COB_BSWAP_32(*(int *)(b_19 + 4))));
  cob_decimal_add (d_0, d_1);
  cob_decimal_get_field (d_0, COB_SET_DATA (f_17, cob_local_ptr), 4);

  /* Line: 16        : MOVE               : C:/work/cobol/examples/calls/sub.cob */
#line 16 "C:/work/cobol/examples/calls/sub.cob"
  module->statement = STMT_MOVE;
#line 164 "sub.c"
  module->module_stmt = 0x00100010;
  memmove (b_19 + 8, cob_local_ptr, 4);

  /* Line: 17        : MOVE               : C:/work/cobol/examples/calls/sub.cob */
#line 17 "C:/work/cobol/examples/calls/sub.cob"
  module->statement = STMT_MOVE;
#line 171 "sub.c"
  module->module_stmt = 0x00100011;
  memcpy (b_19 + 12, "CALLEE    ", 10);

  /* Line: 18        : GOBACK             : C:/work/cobol/examples/calls/sub.cob */
#line 18 "C:/work/cobol/examples/calls/sub.cob"
  module->statement = STMT_GOBACK;
#line 178 "sub.c"
  module->module_stmt = 0x00100012;
  goto exit_program;

  /* Line: 19        : last source line                  :C:/work/cobol/examples/calls/sub.cob */
#line 19 "C:/work/cobol/examples/calls/sub.cob"
  module->module_stmt = 0x00100013;
#line 185 "sub.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Deallocate LOCAL storage */
  if (cob_local_ptr) {
  	cob_free (cob_local_ptr);
  	cob_local_ptr = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  CALLSUB_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output ("WORKING-STORAGE");
    cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_3), 0, 0);

    /* Dump LOCAL-STORAGE SECTION */
    cob_dump_output ("LOCAL-STORAGE");
    cob_dump_field_ext ( 1, "LS-WORK", &f_17, 0, 0);
    cob_dump_field_ext ( 1, "LS-TAG", COB_SET_FLD (f0, 6, cob_local_ptr + 16, &a_4), 0, 0);


    /* Dump LINKAGE SECTION */
    b_19 = last_b_19;
    cob_dump_output ("LINKAGE");
    /* Check LINKAGE address for LK-ARG-REC */
    if (b_19 == NULL)
    {
      cob_dump_field_ext ( 1, "LK-ARG-REC", COB_SET_FLD (f0, 22, NULL, &a_5), 0, 0);
    }
    else
    {
      cob_dump_field_ext ( 1, "LK-ARG-REC", COB_SET_FLD (f0, 22, b_19, &a_5), 0, 0);
      cob_dump_field_ext ( 5, "LK-A", COB_SET_FLD (f0, 4, b_19, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-B", COB_SET_FLD (f0, 4, b_19 + 4, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-SUM", COB_SET_FLD (f0, 4, b_19 + 8, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-NAME", COB_SET_FLD (f0, 10, b_19 + 12, &a_4), 0, 0);
    }

  }
  cob_dump_output ("END OF DUMP - CALLSUB");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CALLSUB' */

/* Initialize module structure for CALLSUB */
static void CALLSUB_module_init (cob_module *module)
{
  module->module_name = "CALLSUB";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())CALLSUB;
  module->module_cancel.funcptr = (void *(*)())CALLSUB_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

