/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/hello.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/hello-dw4/hello -g -fdump=ALL --save-temps -t /work/cobol/build/hello-dw4/hello-dw4.lst -ftsymbols /work/cobol/examples/hello.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/hello.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:06"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144606

/* Global variables */
#include "hello.c.h"

/* Function prototypes */

static int		HELLO ();
static int		HELLO_ (const int);
static void		HELLO_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (HELLO ());
}

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'HELLO' */

/* ENTRY 'HELLO' */

static int
HELLO ()
{
  return HELLO_ (0);
}

static int
HELLO_ (const int entry)
{
  /* Program local variables */
  #include "hello.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (1, &d_0);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "HELLO";
  module->frame_ptr->module_stmt = 0x0010001F;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 31        : Entry     HELLO                   : /work/cobol/examples/hello.cob */
  l_2:;
#line 31 "/work/cobol/examples/hello.cob"
  ENTRY_HELLO:	module->statement = STMT_ENTRY;
#line 113 "hello.c"
  module->module_stmt = 0x0010001F;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 31        : Paragraph 0000-MAIN               : /work/cobol/examples/hello.cob */
#line 31 "/work/cobol/examples/hello.cob"
  PARAGRAPH_0000__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 121 "hello.c"
  module->paragraph_name = st_1;

  /* Line: 32        : PERFORM            : /work/cobol/examples/hello.cob */
#line 32 "/work/cobol/examples/hello.cob"
  module->statement = STMT_PERFORM;
#line 127 "hello.c"
  module->module_stmt = 0x00100020;
  /* PERFORM 1000-INIT */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_8;
  goto l_5;
  l_8:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 33        : PERFORM            : /work/cobol/examples/hello.cob */
#line 33 "/work/cobol/examples/hello.cob"
  module->statement = STMT_PERFORM;
#line 150 "hello.c"
  module->module_stmt = 0x00100021;
  /* PERFORM 2000-COMPUTE */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_9;
  goto l_6;
  l_9:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 34        : PERFORM            : /work/cobol/examples/hello.cob */
#line 34 "/work/cobol/examples/hello.cob"
  module->statement = STMT_PERFORM;
#line 173 "hello.c"
  module->module_stmt = 0x00100022;
  /* PERFORM 3000-REPORT */
  frame_ptr++;
  frame_ptr->module_stmt = module->module_stmt;
  frame_ptr->section_name = module->section_name;
  frame_ptr->paragraph_name = module->paragraph_name;
  module->frame_ptr = frame_ptr;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 7;
  frame_ptr->return_address_ptr = &&l_10;
  goto l_7;
  l_10:
  frame_ptr--;
  module->module_stmt = module->frame_ptr->module_stmt;
  module->section_name = module->frame_ptr->section_name;
  module->paragraph_name = module->frame_ptr->paragraph_name;
  module->frame_ptr = frame_ptr;

  /* Line: 35        : STOP RUN           : /work/cobol/examples/hello.cob */
#line 35 "/work/cobol/examples/hello.cob"
  module->statement = STMT_STOP_RUN;
#line 196 "hello.c"
  module->module_stmt = 0x00100023;
  cob_stop_run (b_2);

  /* Line: 36        : Paragraph 1000-INIT               : /work/cobol/examples/hello.cob */
  l_5:;
#line 36 "/work/cobol/examples/hello.cob"
  PARAGRAPH_1000__INIT_l_5:	module->statement = STMT_ENTRY;
#line 204 "hello.c"
  module->module_stmt = 0x00100024;
  module->paragraph_name = st_2;

  /* Line: 37        : MOVE               : /work/cobol/examples/hello.cob */
#line 37 "/work/cobol/examples/hello.cob"
  module->statement = STMT_MOVE;
#line 211 "hello.c"
  module->module_stmt = 0x00100025;
  cob_move ((cob_field *)&c_2, COB_SET_FLD (f0, cob_get_numdisp (b_33, 1), b_34, &a_3));

  /* Line: 38        : PERFORM            : /work/cobol/examples/hello.cob */
#line 38 "/work/cobol/examples/hello.cob"
  module->statement = STMT_PERFORM;
#line 218 "hello.c"
  module->module_stmt = 0x00100026;
  cob_move ((cob_field *)&c_3, &f_39);
  for (;;)
  {
    /* Line: 38        : UNTIL              : /work/cobol/examples/hello.cob */
#line 38 "/work/cobol/examples/hello.cob"
    module->statement = STMT_UNTIL;
#line 226 "hello.c"
    module->module_stmt = 0x00100026;
    if (((int)cob_cmpswp_u16 (b_39, 5LL) > 0))
      break;

    /* Line: 39        : COMPUTE            : /work/cobol/examples/hello.cob */
#line 39 "/work/cobol/examples/hello.cob"
    module->statement = STMT_COMPUTE;
#line 234 "hello.c"
    module->module_stmt = 0x00100027;
    cob_decimal_set_ullint (d_0, ((unsigned short)COB_BSWAP_16(*(short *)(b_39))));
    cob_decimal_mul (d_0, dc_1);
    cob_decimal_get_field (d_0, COB_SET_FLD (f0, 4, b_30 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_39)))) - 1), &a_6), 0);
    /* Line: 38        : VARYING            : /work/cobol/examples/hello.cob */
#line 38 "/work/cobol/examples/hello.cob"
    module->statement = STMT_VARYING;
#line 242 "hello.c"
    module->module_stmt = 0x00100026;
    cob_addswp_u16 (b_39, 1);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 41        : Paragraph 2000-COMPUTE            : /work/cobol/examples/hello.cob */
  l_6:;
#line 41 "/work/cobol/examples/hello.cob"
  PARAGRAPH_2000__COMPUTE_l_6:	module->statement = STMT_ENTRY;
#line 255 "hello.c"
  module->module_stmt = 0x00100029;
  module->paragraph_name = st_3;

  /* Line: 42        : MOVE               : /work/cobol/examples/hello.cob */
#line 42 "/work/cobol/examples/hello.cob"
  module->statement = STMT_MOVE;
#line 262 "hello.c"
  module->module_stmt = 0x0010002A;
  cob_set_packed_zero (&f_38);

  /* Line: 43        : PERFORM            : /work/cobol/examples/hello.cob */
#line 43 "/work/cobol/examples/hello.cob"
  module->statement = STMT_PERFORM;
#line 269 "hello.c"
  module->module_stmt = 0x0010002B;
  cob_move ((cob_field *)&c_3, &f_39);
  for (;;)
  {
    /* Line: 43        : UNTIL              : /work/cobol/examples/hello.cob */
#line 43 "/work/cobol/examples/hello.cob"
    module->statement = STMT_UNTIL;
#line 277 "hello.c"
    module->module_stmt = 0x0010002B;
    if (((int)cob_cmpswp_u16 (b_39, 5LL) > 0))
      break;

    /* Line: 44        : ADD                : /work/cobol/examples/hello.cob */
#line 44 "/work/cobol/examples/hello.cob"
    module->statement = STMT_ADD;
#line 285 "hello.c"
    module->module_stmt = 0x0010002C;
    cob_add_int (&f_38, cob_get_numdisp (b_30 + 4LL * ((cob_s64_t)(((unsigned short)COB_BSWAP_16(*(short *)(b_39)))) - 1), 4), 0);
    /* Line: 43        : VARYING            : /work/cobol/examples/hello.cob */
#line 43 "/work/cobol/examples/hello.cob"
    module->statement = STMT_VARYING;
#line 291 "hello.c"
    module->module_stmt = 0x0010002B;
    cob_addswp_u16 (b_39, 1);
  }

  /* Line: 46        : ADD                : /work/cobol/examples/hello.cob */
#line 46 "/work/cobol/examples/hello.cob"
  module->statement = STMT_ADD;
#line 299 "hello.c"
  module->module_stmt = 0x0010002E;
  cob_add (&f_38, &f_19, 0);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 47        : Paragraph 3000-REPORT             : /work/cobol/examples/hello.cob */
  l_7:;
#line 47 "/work/cobol/examples/hello.cob"
  PARAGRAPH_3000__REPORT_l_7:	module->statement = STMT_ENTRY;
#line 311 "hello.c"
  module->module_stmt = 0x0010002F;
  module->paragraph_name = st_4;

  /* Line: 48        : DISPLAY            : /work/cobol/examples/hello.cob */
#line 48 "/work/cobol/examples/hello.cob"
  module->statement = STMT_DISPLAY;
#line 318 "hello.c"
  module->module_stmt = 0x00100030;
  cob_display (0, 1, 2, &c_4, &f_38);

  /* Line: 49        : DISPLAY            : /work/cobol/examples/hello.cob */
#line 49 "/work/cobol/examples/hello.cob"
  module->statement = STMT_DISPLAY;
#line 325 "hello.c"
  module->module_stmt = 0x00100031;
  cob_display (0, 1, 4, &c_5, &f_26, &c_6, &f_25);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 50        : last source line                  :/work/cobol/examples/hello.cob */
#line 50 "/work/cobol/examples/hello.cob"
  module->module_stmt = 0x00100032;
#line 336 "hello.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  HELLO_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-ALPHA */
#line 6 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 390 "hello.c"
  memcpy (b_17, "HELLO       ", 12);

  /* initialize field WS-U */
#line 7 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 396 "hello.c"
  memcpy (b_18, "12345", 5);

  /* initialize field WS-SCALED */
#line 8 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 402 "hello.c"
  memcpy (b_19, "001234u", 7);

  /* initialize field WS-BINARY */
#line 9 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 408 "hello.c"
  cob_move ((cob_field *)&c_7, COB_SET_FLD (f0, 4, b_20, &a_11));

  /* initialize field WS-PACKED */
#line 10 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 414 "hello.c"
  cob_move ((cob_field *)&c_8, COB_SET_FLD (f0, 5, b_21, &a_7));

  /* initialize field WS-COMP5 */
#line 11 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 420 "hello.c"
  cob_move ((cob_field *)&c_9, COB_SET_FLD (f0, 4, b_22, &a_14));

  /* initialize field WS-DOUBLE */
#line 12 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 426 "hello.c"
  cob_move ((cob_field *)&c_10, COB_SET_FLD (f0, 8, b_23, &a_16));

  /* initialize field WS-ID */
#line 14 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 432 "hello.c"
  memcpy (b_24, "0042", 4);
  /* initialize field WS-NAME */
#line 15 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 437 "hello.c"
  memcpy (b_24 + 4, "ALICE               ", 20);
  /* initialize field WS-STATUS */
#line 16 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 442 "hello.c"
  *(cob_u8_ptr)(b_24 + 24) = (unsigned char)'A';

  /* initialize field WS-TABLE */
#line 19 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 448 "hello.c"
  memset (b_30, (unsigned char)'0', 20);

  /* initialize field WS-COUNT */
#line 22 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 454 "hello.c"
  *(b_33) = 51;

  /* initialize field WS-ODO */
#line 23 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 460 "hello.c"
  memset (b_34, (unsigned char)' ', 9);

  /* initialize field WS-RAW */
#line 26 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 466 "hello.c"
  memcpy (b_36, "00001234", 8);


  /* initialize field WS-TOTAL */
#line 28 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 473 "hello.c"
  cob_set_packed_zero (&f_38);

  /* initialize field WS-IDX */
#line 29 "/work/cobol/examples/hello.cob"
  cob_nop ();
#line 479 "hello.c"
  cob_move ((cob_field *)&c_11, &f_39);


  /* Set Decimal Constant values */
  dc_1 = &kc_1;
  cob_decimal_init (dc_1);
  cob_decimal_set_field (dc_1, (cob_field *)&c_1);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump WORKING-STORAGE */
  cob_dump_output ("WORKING-STORAGE");
  cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_17), 0, 0);
  cob_dump_field_ext ( 1, "WS-ALPHA", COB_SET_FLD (f0, 12, b_17, &a_9), 0, 0);
  cob_dump_field_ext ( 1, "WS-U", COB_SET_FLD (f0, 5, b_18, &a_18), 0, 0);
  cob_dump_field_ext ( 1, "WS-SCALED", &f_19, 0, 0);
  cob_dump_field_ext ( 1, "WS-BINARY", COB_SET_FLD (f0, 4, b_20, &a_11), 0, 0);
  cob_dump_field_ext ( 1, "WS-PACKED", COB_SET_FLD (f0, 5, b_21, &a_7), 0, 0);
  cob_dump_field_ext ( 1, "WS-COMP5", COB_SET_FLD (f0, 4, b_22, &a_14), 0, 0);
  cob_dump_field_ext ( 1, "WS-DOUBLE", COB_SET_FLD (f0, 8, b_23, &a_16), 0, 0);
  cob_dump_field_ext ( 1, "WS-GROUP", COB_SET_FLD (f0, 25, b_24, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "WS-ID", &f_25, 0, 0);
  cob_dump_field_ext ( 5, "WS-NAME", &f_26, 0, 0);
  cob_dump_field_ext ( 5, "WS-STATUS", COB_SET_FLD (f0, 1, b_24 + 24, &a_9), 0, 0);
  /* cob_dump_field_ext (88, "WS-STATUS-ACTIVE", COB_SET_FLD (f0, 1, b_24 + 24, &a_9), 0, 0); VALUE (cob_field *)&c_12 */
  /* cob_dump_field_ext (88, "WS-STATUS-CLOSED", COB_SET_FLD (f0, 1, b_24 + 24, &a_9), 0, 0); VALUE (cob_field *)&c_13 OR (cob_field *)&c_14 */
  cob_dump_field_ext ( 1, "WS-TABLE", COB_SET_FLD (f0, 20, b_30, &a_3), 0, 0);
  {
    int i_1;
    int max_1 = 5;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ENTRY", COB_SET_FLD (f0, 4, b_30, &a_3), 0, 1, i_1, 4UL); /* OCCURS 1 5 */
      cob_dump_field_ext (10, "WS-AMOUNT", &f_32, 0, 1, i_1, 4UL);
    }
  }
  cob_dump_field_ext ( 1, "WS-COUNT", &f_33, 0, 0);
  cob_dump_field_ext ( 1, "WS-ODO", COB_SET_FLD (f0, cob_get_numdisp (b_33, 1), b_34, &a_3), 0, 0);
  {
    int i_1;
    int max_1 = cob_get_numdisp (b_33, 1);
    if (max_1 > 9) max_1 = 9;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ITEM", COB_SET_FLD (f0, 1, b_34, &a_9), 0, 1, i_1, 1UL); /* OCCURS 1 9 */
    }
  }
  cob_dump_field_ext ( 1, "WS-RAW", COB_SET_FLD (f0, 8, b_36, &a_9), 0, 0);
  /* cob_dump_field_ext ( 1, "WS-ALT", COB_SET_FLD (f0, 8, b_36, &a_20), 0, 0); REDEFINES */
  cob_dump_field_ext ( 1, "WS-TOTAL", &f_38, 0, 0);
  cob_dump_field_ext ( 1, "WS-IDX", &f_39, 0, 0);

  cob_dump_output ("END OF DUMP - HELLO");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  /* Clear Decimal Constant values */
  cob_decimal_clear (dc_1);
  dc_1 = NULL;

  return 0;

}

/* End PROGRAM-ID 'HELLO' */

/* Initialize module structure for HELLO */
static void HELLO_module_init (cob_module *module)
{
  module->module_name = "HELLO";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())HELLO;
  module->module_cancel.funcptr = (void *(*)())HELLO_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

