/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/hello.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/hello-dw4/hello -g -fdump=ALL --save-temps -t /work/cobol/build/hello-dw4/hello-dw4.lst -ftsymbols /work/cobol/examples/hello.cob */

/* Program local variables for 'HELLO' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d_0 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[12] __attribute__((aligned));	/* WS-ALPHA */
static cob_u8_t	b_18[5] __attribute__((aligned));	/* WS-U */
static cob_u8_t	b_19[7] __attribute__((aligned));	/* WS-SCALED */
static cob_u8_t	b_20[4] __attribute__((aligned));	/* WS-BINARY */
static cob_u8_t	b_21[5] __attribute__((aligned));	/* WS-PACKED */
static cob_u8_t	b_22[4] __attribute__((aligned));	/* WS-COMP5 */
static cob_u8_t	b_23[8] __attribute__((aligned));	/* WS-DOUBLE */
static cob_u8_t	b_24[25] __attribute__((aligned));	/* WS-GROUP */
static cob_u8_t	b_30[20] __attribute__((aligned));	/* WS-TABLE */
static cob_u8_t	b_33[1] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_34[9] __attribute__((aligned));	/* WS-ODO */
static cob_u8_t	b_36[8] __attribute__((aligned));	/* WS-RAW */
static cob_u8_t	b_38[5] __attribute__((aligned));	/* WS-TOTAL */
static cob_u8_t	b_39[2] __attribute__((aligned));	/* WS-IDX */

/* End of local data storage */


/* Fields (local) */
static cob_field f_19	= {7, b_19, &a_8};	/* WS-SCALED */
static cob_field f_25	= {4, b_24, &a_6};	/* WS-ID */
static cob_field f_26	= {20, b_24 + 4, &a_9};	/* WS-NAME */
static cob_field f_32	= {4, b_30, &a_6};	/* WS-AMOUNT */
static cob_field f_33	= {1, b_33, &a_19};	/* WS-COUNT */
static cob_field f_38	= {5, b_38, &a_7};	/* WS-TOTAL */
static cob_field f_39	= {2, b_39, &a_5};	/* WS-IDX */

/* End of fields */

