/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/calls/main.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x11,   9,   0, 0x0821, NULL};
static const cob_field_attr a_4 =	{0x10,   4,   0, 0x1000, NULL};
static const cob_field_attr a_5 =	{0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_6 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_7 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {11, (cob_u8_ptr)"before call", &a_1};
static const cob_field c_2	= {24, (cob_u8_ptr)"COBOL_DEBUG_MARKER: sum=", &a_1};
static const cob_field c_3	= {4, (cob_u8_ptr)"1000", &a_4};
static const cob_field c_4	= {3, (cob_u8_ptr)"234", &a_5};
static const cob_field c_5	= {1, (cob_u8_ptr)"0", &a_6};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "CALL";
static const char st_3[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/work/cobol/examples/calls/main.cob"};
