/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/calls/main.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */

/* Program local variables for 'CALLMAIN' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_CALLSUB;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[22] __attribute__((aligned));	/* WS-ARG-REC */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {22, b_8, &a_2};	/* WS-ARG-REC */
static cob_field f_11	= {4, b_8 + 8, &a_3};	/* WS-ARG-SUM */

/* End of fields */

