/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/calls/main.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/calls/main.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:09"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144609

/* Global variables */
#include "main.c.h"

/* Function prototypes */

static int		CALLMAIN ();
static int		CALLMAIN_ (const int);
static void		CALLMAIN_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CALLMAIN ());
}

/* Functions */

/* PROGRAM-ID 'CALLMAIN' */

/* ENTRY 'CALLMAIN' */

static int
CALLMAIN ()
{
  return CALLMAIN_ (0);
}

static int
CALLMAIN_ (const int entry)
{
  /* Program local variables */
  #include "main.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     CALLMAIN                : /work/cobol/examples/calls/main.cob */
  l_2:;
#line 10 "/work/cobol/examples/calls/main.cob"
  ENTRY_CALLMAIN:;
#line 100 "main.c"
#line 11 "/work/cobol/examples/calls/main.cob"
  SECTION_MAIN_20SECTION:;
#line 103 "main.c"

  /* Line: 11        : Paragraph 0000-MAIN               : /work/cobol/examples/calls/main.cob */
#line 11 "/work/cobol/examples/calls/main.cob"
  cob_nop ();
#line 108 "main.c"

  /* Line: 12        : DISPLAY            : /work/cobol/examples/calls/main.cob */
  module->module_stmt = 0x0010000C;
#line 12 "/work/cobol/examples/calls/main.cob"
  cob_trace_stmt (st_1);
#line 114 "main.c"
  cob_display (0, 1, 1, &c_1);

  /* Line: 13        : CALL               : /work/cobol/examples/calls/main.cob */
  module->module_stmt = 0x0010000D;
#line 13 "/work/cobol/examples/calls/main.cob"
  cob_trace_stmt (st_2);
#line 121 "main.c"
  cob_procedure_params[0] = &f_8;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
    if (unlikely(call_CALLSUB.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_CALLSUB.funcvoid = cob_resolve_cobol ("CALLSUB", 0, 1);
  }
  b_2 = ((int (*)(void *))call_CALLSUB.funcint) (b_8);

  /* Line: 14        : DISPLAY            : /work/cobol/examples/calls/main.cob */
  module->module_stmt = 0x0010000E;
#line 14 "/work/cobol/examples/calls/main.cob"
  cob_trace_stmt (st_1);
#line 136 "main.c"
  cob_display (0, 1, 2, &c_2, &f_11);

  /* Line: 15        : STOP RUN           : /work/cobol/examples/calls/main.cob */
  module->module_stmt = 0x0010000F;
#line 15 "/work/cobol/examples/calls/main.cob"
  cob_trace_stmt (st_3);
#line 143 "main.c"
  cob_stop_run (b_2);

  module->module_stmt = 0x00100010;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CALLMAIN_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  cob_move ((cob_field *)&c_3, COB_SET_FLD(f0, 4, b_8, &a_3));
  cob_move ((cob_field *)&c_4, COB_SET_FLD(f0, 4, b_8 + 4, &a_3));
  cob_move ((cob_field *)&c_5, &f_11);
  memcpy (b_8 + 12, "CALLER", 6);
  memset (b_8 + 12 + 6, 32, 4);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump WORKING-STORAGE */
  cob_dump_output("WORKING-STORAGE");
  cob_dump_field_ext ( 1, "WS-ARG-REC", &f_8, 0, 0);
  cob_dump_field_ext ( 5, "WS-ARG-A", COB_SET_FLD(f0, 4, b_8, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "WS-ARG-B", COB_SET_FLD(f0, 4, b_8 + 4, &a_3), 0, 0);
  cob_dump_field_ext ( 5, "WS-ARG-SUM", &f_11, 0, 0);
  cob_dump_field_ext ( 5, "WS-ARG-NAME", COB_SET_FLD(f0, 10, b_8 + 12, &a_7), 0, 0);

  cob_dump_output("END OF DUMP - CALLMAIN");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CALLMAIN' */

/* Initialize module structure for CALLMAIN */
static void CALLMAIN_module_init (cob_module *module)
{
  module->module_name = "CALLMAIN";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CALLMAIN;
  module->module_cancel.funcptr = (void *(*)())CALLMAIN_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

