/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/calls/sub.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/calls/sub.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:09"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144609

/* Global variables */
#include "sub.c.h"

/* Function prototypes */

int		CALLSUB (cob_u8_t *);
static int		CALLSUB_ (const int, cob_u8_t *);
static void		CALLSUB_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'CALLSUB' */

/* ENTRY 'CALLSUB' */

int
CALLSUB (cob_u8_t *b_10)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
  	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
  	cob_call_params = 1;
  };

  return CALLSUB_ (0, b_10);
}

static int
CALLSUB_ (const int entry, cob_u8_t *b_10)
{
  /* Program local variables */
  #include "sub.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Allocate LOCAL storage */
  cob_local_ptr = cob_malloc (32U);

  /* Initialize LOCAL storage */
  cob_move ((cob_field *)&c_1, COB_SET_DATA (f_8, cob_local_ptr));
  memcpy (cob_local_ptr + 16, "LOCAL ", 6);

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_10 = NULL;
  /* Fall through */
  default:
  	break; 
  }

  /* Store last parameters for possible later lookup */
  last_b_10 = b_10;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 13        : Entry     CALLSUB                 : /work/cobol/examples/calls/sub.cob */
  l_2:;
#line 13 "/work/cobol/examples/calls/sub.cob"
  ENTRY_CALLSUB:;
#line 123 "sub.c"
#line 14 "/work/cobol/examples/calls/sub.cob"
  SECTION_MAIN_20SECTION:;
#line 126 "sub.c"

  /* Line: 14        : Paragraph 0000-SUB-MAIN           : /work/cobol/examples/calls/sub.cob */
#line 14 "/work/cobol/examples/calls/sub.cob"
  cob_nop ();
#line 131 "sub.c"

  /* Line: 15        : ADD                : /work/cobol/examples/calls/sub.cob */
  module->module_stmt = 0x0010000F;
#line 15 "/work/cobol/examples/calls/sub.cob"
  cob_trace_stmt (st_1);
#line 137 "sub.c"
  cob_decimal_set_llint (d0, ((int)COB_BSWAP_32(*(int *)(b_10))));
  cob_decimal_set_llint (d1, ((int)COB_BSWAP_32(*(int *)(b_10 + 4))));
  cob_decimal_add (d0, d1);
  cob_decimal_get_field (d0, COB_SET_DATA (f_8, cob_local_ptr), 4);

  /* Line: 16        : MOVE               : /work/cobol/examples/calls/sub.cob */
  module->module_stmt = 0x00100010;
#line 16 "/work/cobol/examples/calls/sub.cob"
  cob_trace_stmt (st_2);
#line 147 "sub.c"
  memmove (b_10 + 8, cob_local_ptr, 4);

  /* Line: 17        : MOVE               : /work/cobol/examples/calls/sub.cob */
  module->module_stmt = 0x00100011;
#line 17 "/work/cobol/examples/calls/sub.cob"
  cob_trace_stmt (st_2);
#line 154 "sub.c"
  memcpy (b_10 + 12, "CALLEE    ", 10);

  /* Line: 18        : GOBACK             : /work/cobol/examples/calls/sub.cob */
  module->module_stmt = 0x00100012;
#line 18 "/work/cobol/examples/calls/sub.cob"
  cob_trace_stmt (st_3);
#line 161 "sub.c"
  goto exit_program;

  module->module_stmt = 0x00100013;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Deallocate LOCAL storage */
  if (cob_local_ptr) {
  	cob_free (cob_local_ptr);
  	cob_local_ptr = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  CALLSUB_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output("WORKING-STORAGE");

    /* Dump LOCAL-STORAGE SECTION */
    cob_dump_output("LOCAL-STORAGE");
    cob_dump_field_ext ( 1, "LS-WORK", &f_8, 0, 0);
    cob_dump_field_ext ( 1, "LS-TAG", COB_SET_FLD(f0, 6, cob_local_ptr + 16, &a_3), 0, 0);


    /* Dump LINKAGE SECTION */
    b_10 = last_b_10;
    cob_dump_output("LINKAGE");
    /* Check LINKAGE address for LK-ARG-REC */
    if (b_10 == NULL)
    {
      cob_dump_field_ext ( 1, "LK-ARG-REC", COB_SET_FLD(f0, 22, NULL, &a_4), 0, 0);
    }
    else
    {
      cob_dump_field_ext ( 1, "LK-ARG-REC", COB_SET_FLD(f0, 22, b_10, &a_4), 0, 0);
      cob_dump_field_ext ( 5, "LK-A", COB_SET_FLD(f0, 4, b_10, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-B", COB_SET_FLD(f0, 4, b_10 + 4, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-SUM", COB_SET_FLD(f0, 4, b_10 + 8, &a_2), 0, 0);
      cob_dump_field_ext ( 5, "LK-NAME", COB_SET_FLD(f0, 10, b_10 + 12, &a_3), 0, 0);
    }

  }
  cob_dump_output("END OF DUMP - CALLSUB");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CALLSUB' */

/* Initialize module structure for CALLSUB */
static void CALLSUB_module_init (cob_module *module)
{
  module->module_name = "CALLSUB";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CALLSUB;
  module->module_cancel.funcptr = (void *(*)())CALLSUB_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 1;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

