/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 14:46:10 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x --debug -A -O0 -gdwarf-4 -o /work/cobol/build/rterror/rterror -g -fdump=ALL --save-temps -t /work/cobol/build/rterror/rterror.lst -ftsymbols /work/cobol/examples/rterror.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   4,   0, 0x0820, NULL};
static const cob_field_attr a_3 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"5", &a_1};
static const cob_field c_2	= {15, (cob_u8_ptr)"about to index ", &a_3};
static const cob_field c_3	= {24, (cob_u8_ptr)"COBOL_DEBUG_MARKER: sum=", &a_3};
static const cob_field c_4	= {1, (cob_u8_ptr)"0", &a_1};


/* Strings */
static const char st_1[]	= "RTERROR";
static const char st_2[]	= "0000-MAIN";
static const char st_3[]	= "MOVE";
static const char st_4[]	= "DISPLAY";
static const char st_5[]	= "ADD";
static const char st_6[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/work/cobol/examples/rterror.cob"};

static int COB_NOINLINE
cob_get_numdisp (const void *data, const int size)
{
	const unsigned char	*p;
	int			n;
	int 			retval;
	p = (const unsigned char *)data;
	retval = 0;
	for (n = 0; n < size; ++n, ++p) {
		retval *= 10;
		if (*p > '0' && *p <= '9')
		    retval += (*p - '0');
	}
	return retval;
}

