/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 14:46:10 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x --debug -A -O0 -gdwarf-4 -o /work/cobol/build/rterror/rterror -g -fdump=ALL --save-temps -t /work/cobol/build/rterror/rterror.lst -ftsymbols /work/cobol/examples/rterror.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/rterror.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:10"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144610

/* Global variables */
#include "rterror.c.h"

/* Function prototypes */

static int		RTERROR ();
static int		RTERROR_ (const int);
static void		RTERROR_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (RTERROR ());
}

/* Functions */

/* PROGRAM-ID 'RTERROR' */

/* ENTRY 'RTERROR' */

static int
RTERROR ()
{
  return RTERROR_ (0);
}

static int
RTERROR_ (const int entry)
{
  /* Program local variables */
  #include "rterror.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 9         : Entry     RTERROR                 : /work/cobol/examples/rterror.cob */
  l_2:;
#line 9 "/work/cobol/examples/rterror.cob"
  ENTRY_RTERROR:;
#line 100 "rterror.c"
  module->module_stmt = 0x00100009;
  cob_trace_entry (st_1);
#line 10 "/work/cobol/examples/rterror.cob"
  SECTION_MAIN_20SECTION:;
#line 105 "rterror.c"
  module->module_stmt = 0x0010000A;
  cob_trace_sect (NULL);

  /* Line: 10        : Paragraph 0000-MAIN               : /work/cobol/examples/rterror.cob */
#line 10 "/work/cobol/examples/rterror.cob"
  cob_nop ();
#line 112 "rterror.c"
  cob_trace_para (st_2);

  /* Line: 11        : MOVE               : /work/cobol/examples/rterror.cob */
  module->module_stmt = 0x0010000B;
#line 11 "/work/cobol/examples/rterror.cob"
  cob_trace_stmt (st_3);
#line 119 "rterror.c"
  cob_move ((cob_field *)&c_1, &f_10);

  /* Line: 12        : DISPLAY            : /work/cobol/examples/rterror.cob */
  module->module_stmt = 0x0010000C;
#line 12 "/work/cobol/examples/rterror.cob"
  cob_trace_stmt (st_4);
#line 126 "rterror.c"
  cob_display (0, 1, 2, &c_2, &f_10);

  /* Line: 13        : ADD                : /work/cobol/examples/rterror.cob */
  module->module_stmt = 0x0010000D;
#line 13 "/work/cobol/examples/rterror.cob"
  cob_trace_stmt (st_5);
#line 133 "rterror.c"
  cob_check_numeric (
  (cob_check_subscript (((unsigned short)COB_BSWAP_16(*(short *)(b_10))), 3, "WS-CELL", 0),
  COB_SET_FLD(f0, 3, b_8 + 3 * (((short)COB_BSWAP_16(*(short *)(b_10))) - 1), &a_4) ), "WS-CELL");
  cob_check_numeric (&f_11, "WS-SUM");
  cob_add_int (&f_11, cob_get_numdisp (b_8 + 3 * (((short)COB_BSWAP_16(*(short *)(b_10))) - 1), 3), 0);

  /* Line: 14        : DISPLAY            : /work/cobol/examples/rterror.cob */
  module->module_stmt = 0x0010000E;
#line 14 "/work/cobol/examples/rterror.cob"
  cob_trace_stmt (st_4);
#line 144 "rterror.c"
  cob_display (0, 1, 2, &c_3, &f_11);

  /* Line: 15        : STOP RUN           : /work/cobol/examples/rterror.cob */
  module->module_stmt = 0x0010000F;
#line 15 "/work/cobol/examples/rterror.cob"
  cob_trace_stmt (st_6);
#line 151 "rterror.c"
  cob_stop_run (b_2);

  module->module_stmt = 0x00100010;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  RTERROR_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  /* initialize first record for WS-CELL */
  memcpy (b_8, "007", 3);
  /* copy initialized record for WS-CELL to later occurrences */
  {
    cob_u8_ptr b_ptr = b_8;
    memcpy (b_ptr +      3, b_ptr,      3);	/* WS-CELL:      2 thru 2 */
    memcpy (b_ptr +      6, b_ptr,      3);	/* WS-CELL:      3 thru 3 */
  }
  cob_move ((cob_field *)&c_4, &f_10);
  memset (b_11, 48, 6);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump WORKING-STORAGE */
  cob_dump_output("WORKING-STORAGE");
  cob_dump_field_ext ( 1, "WS-TABLE", COB_SET_FLD(f0, 9, b_8, &a_6), 0, 0);
  {
    int i_1;
    int max_1 = 3;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-CELL", &f_9, 0, 1, i_1, 3UL); /* OCCURS 1 3 */
    }
  }
  cob_dump_field_ext ( 1, "WS-IDX", &f_10, 0, 0);
  cob_dump_field_ext ( 1, "WS-SUM", &f_11, 0, 0);

  cob_dump_output("END OF DUMP - RTERROR");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'RTERROR' */

/* Initialize module structure for RTERROR */
static void RTERROR_module_init (cob_module *module)
{
  module->module_name = "RTERROR";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())RTERROR;
  module->module_cancel.funcptr = (void *(*)())RTERROR_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

