/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/rterror.cob */
/* Generated at           Sep 19 2026 14:46:10 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x --debug -A -O0 -gdwarf-4 -o /work/cobol/build/rterror/rterror -g -fdump=ALL --save-temps -t /work/cobol/build/rterror/rterror.lst -ftsymbols /work/cobol/examples/rterror.cob */

/* Program local variables for 'RTERROR' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[9] __attribute__((aligned));	/* WS-TABLE */
static cob_u8_t	b_10[2] __attribute__((aligned));	/* WS-IDX */
static cob_u8_t	b_11[6] __attribute__((aligned));	/* WS-SUM */

/* End of local data storage */


/* Fields (local) */
static cob_field f_9	= {3, b_8, &a_4};	/* WS-CELL */
static cob_field f_10	= {2, b_10, &a_2};	/* WS-IDX */
static cob_field f_11	= {6, b_11, &a_5};	/* WS-SUM */

/* End of fields */

