/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 19:47:10 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -g -fdump=ALL -t /work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm /work/cobol/examples/shapes.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 2},
	{',', 1},
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x24,   7,   2, 0x0000, p_1};
static const cob_field_attr a_5 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x10,   5,   1, 0x1000, NULL};
static const cob_field_attr a_8 =	{0x10,   8,   2, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_10 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x10,   1,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"4", &a_1};
static const cob_field c_2	= {7, (cob_u8_ptr)"SHAPES ", &a_2};
static const cob_field c_3	= {1, (cob_u8_ptr)" ", &a_2};
static const cob_field c_4	= {5, (cob_u8_ptr)"12345", &a_7};
static const cob_field c_5	= {10, (cob_u8_ptr)"shapes.dat", &a_2};


/* Strings */
static const char st_1[]	= "0000-MAIN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/work/cobol/examples/shapes.cob"};

#define cob_nop	if (!module) cob_nop


static int COB_INLINE COB_A_INLINE
cob_get_numdisp (const void *data, const int size)
{
	register const unsigned char	*p = (const unsigned char *)data;
	register int	n;
	register int	val = 0;
	for (n = 0; n < val; ++n, ++p) {
		if (*p > '0' && *p <= '9')
			break;
	}
	for (n = 0; n < size; ++n, ++p) {
		val = (val * 10)
		    + (*p & 0x0F);
	}
	return val;
}

