/* Generated by           cobc 3.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:59:00 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   3,   5, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   5,  -2, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   3,   5, 0x0007, NULL};
static const cob_field_attr a_4 =	{0x10,   5,  -2, 0x0003, NULL};
static const cob_field_attr a_5 =	{0x12,   3,   5, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x12,   5,  -2, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x11,   3,   5, 0x0820, NULL};
static const cob_field_attr a_8 =	{0x11,   5,  -2, 0x0820, NULL};
static const cob_field_attr a_9 =	{0x1b,   9,   0, 0x0041, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"../scaling.cob"};

#define cob_nop	if (!module) cob_nop

