/* Generated by           cobc 3.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:59:00 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"../scaling.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 20 2026 22:59:00"
#define  COB_MODULE_DATE		20260920
#define  COB_MODULE_TIME		225900

/* Global variables */
#include "scaling.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		SCALING (void);
static int		SCALING_ (const int);
static void		SCALING_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'SCALING' */

/* ENTRY 'SCALING' */

int
SCALING ()
{
  return SCALING_ (0);
}

static int
SCALING_ (const int entry)
{
  /* Program local variables */
  #include "scaling.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "SCALING";
  module->frame_ptr->module_stmt = 0x0010000F;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 15        : Entry     SCALING                 : ../scaling.cob */
  l_2:;
#line 15 "../scaling.cob"
  ENTRY_SCALING:	module->statement = STMT_ENTRY;
#line 101 "scaling.c"
  module->module_stmt = 0x0010000F;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 15        : DISPLAY            : ../scaling.cob */
#line 15 "../scaling.cob"
  module->statement = STMT_DISPLAY;
#line 109 "scaling.c"
  cob_display (0, 1, 8, &f_17, &f_18, &f_19, &f_20, &f_21, &f_22, &f_23, &f_24);

  /* Line: 17        : GOBACK             : ../scaling.cob */
#line 17 "../scaling.cob"
  module->statement = STMT_GOBACK;
#line 115 "scaling.c"
  module->module_stmt = 0x00100011;
  goto exit_program;

  /* Line: 18        : last source line                  :../scaling.cob */
#line 18 "../scaling.cob"
  module->module_stmt = 0x00100012;
#line 122 "scaling.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  SCALING_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field LEAD-D */
#line 6 "../scaling.cob"
  cob_nop ();
#line 174 "scaling.c"
  memset (b_17, (unsigned char)'0', 3);

  /* initialize field TRAIL-D */
#line 7 "../scaling.cob"
  cob_nop ();
#line 180 "scaling.c"
  memset (b_18, (unsigned char)'0', 3);

  /* initialize field LEAD-S */
#line 8 "../scaling.cob"
  cob_nop ();
#line 186 "scaling.c"
  cob_move (&cob_all_zero, &f_19);

  /* initialize field TRAIL-S */
#line 9 "../scaling.cob"
  cob_nop ();
#line 192 "scaling.c"
  cob_move (&cob_all_zero, &f_20);

  /* initialize field LEAD-P */
#line 10 "../scaling.cob"
  cob_nop ();
#line 198 "scaling.c"
  cob_set_packed_zero (&f_21);

  /* initialize field TRAIL-P */
#line 11 "../scaling.cob"
  cob_nop ();
#line 204 "scaling.c"
  cob_set_packed_zero (&f_22);

  /* initialize field LEAD-B */
#line 12 "../scaling.cob"
  cob_nop ();
#line 210 "scaling.c"
  memset (b_23, 0x0, 2);

  /* initialize field TRAIL-B */
#line 13 "../scaling.cob"
  cob_nop ();
#line 216 "scaling.c"
  memset (b_24, 0x0, 2);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output ("WORKING-STORAGE");
    cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_9), 0, 0);
    cob_dump_field_ext ( 1, "LEAD-D", &f_17, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-D", &f_18, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-S", &f_19, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-S", &f_20, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-P", &f_21, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-P", &f_22, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-B", &f_23, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-B", &f_24, 0, 0);

  }
  cob_dump_output ("END OF DUMP - SCALING");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'SCALING' */

/* Initialize module structure for SCALING */
static void SCALING_module_init (cob_module *module)
{
  module->module_name = "SCALING";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())SCALING;
  module->module_cancel.funcptr = (void *(*)())SCALING_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

