/* Generated by           cobc 3.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:59:00 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */

/* Program local variables for 'SCALING' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[3] __attribute__((aligned));	/* LEAD-D */
static cob_u8_t	b_18[3] __attribute__((aligned));	/* TRAIL-D */
static cob_u8_t	b_19[4] __attribute__((aligned));	/* LEAD-S */
static cob_u8_t	b_20[4] __attribute__((aligned));	/* TRAIL-S */
static cob_u8_t	b_21[2] __attribute__((aligned));	/* LEAD-P */
static cob_u8_t	b_22[2] __attribute__((aligned));	/* TRAIL-P */
static cob_u8_t	b_23[2] __attribute__((aligned));	/* LEAD-B */
static cob_u8_t	b_24[2] __attribute__((aligned));	/* TRAIL-B */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {3, b_17, &a_1};	/* LEAD-D */
static cob_field f_18	= {3, b_18, &a_2};	/* TRAIL-D */
static cob_field f_19	= {4, b_19, &a_3};	/* LEAD-S */
static cob_field f_20	= {4, b_20, &a_4};	/* TRAIL-S */
static cob_field f_21	= {2, b_21, &a_5};	/* LEAD-P */
static cob_field f_22	= {2, b_22, &a_6};	/* TRAIL-P */
static cob_field f_23	= {2, b_23, &a_7};	/* LEAD-B */
static cob_field f_24	= {2, b_24, &a_8};	/* TRAIL-B */

/* End of fields */

