/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 19:47:11 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL -t /work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm /work/cobol/examples/shapes.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/shapes.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 19:47:11"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		194711

/* Global variables */
#include "shapes.c.h"

/* Function prototypes */

int		shapes (void);
static int		shapes_ (const int);
static void		shapes_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'shapes' */

/* ENTRY 'shapes' */

int
shapes ()
{
  return shapes_ (0);
}

static int
shapes_ (const int entry)
{
  /* Program local variables */
  #include "shapes.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Allocate LOCAL storage */
  cob_local_ptr = cob_malloc (32U);

  /* Initialize LOCAL storage */
  memset (cob_local_ptr, 32, 4);
  memset (cob_local_ptr + 16, 32, 4);
  *(cob_local_ptr + 16 + 4) = 50;
  memset (cob_local_ptr + 16 + 5, 32, 9);

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 89        : Entry     shapes                  : /work/cobol/examples/shapes.cob */
  l_2:;
#line 89 "/work/cobol/examples/shapes.cob"
  ENTRY_SHAPES:;
#line 101 "shapes.c"
#line 90 "/work/cobol/examples/shapes.cob"
  SECTION_MAIN_20SECTION:;
#line 104 "shapes.c"

  /* Line: 90        : Paragraph 0000-MAIN               : /work/cobol/examples/shapes.cob */
#line 90 "/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 109 "shapes.c"

  /* Line: 91        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010005B;
#line 91 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 115 "shapes.c"
  memcpy (b_16 + 6 * 1, "1234", 4);

  /* Line: 92        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010005C;
#line 92 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 122 "shapes.c"
  memcpy (b_16 + 4 + 6 * 1, "AB", 2);

  /* Line: 93        : SET                : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010005D;
#line 93 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_2);
#line 129 "shapes.c"
  b_18 = 3;

  /* Line: 94        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010005E;
#line 94 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 136 "shapes.c"
  memcpy (b_22 + 2 * 1, "XY", 2);

  /* Line: 95        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010005F;
#line 95 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 143 "shapes.c"
  memcpy (cob_local_ptr + 16, "AB", 2);

  /* Line: 96        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100060;
#line 96 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 150 "shapes.c"
  memcpy (cob_local_ptr + 16 + 2, "CD", 2);

  /* Line: 97        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100061;
#line 97 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 157 "shapes.c"
  memset (cob_local_ptr + 16 + 5 + 3 * 1, 81, 3);

  /* Line: 98        : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100062;
#line 98 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 164 "shapes.c"
  memcpy (b_27, "external! ", 10);

  /* Line: 99        : ALLOCATE           : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100063;
#line 99 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_3);
#line 171 "shapes.c"
  cob_glob_ptr->cob_exception_code = 0;
  cob_allocate (&b_28, NULL, (cob_field *)&c_1, NULL);
  if (!cob_glob_ptr->cob_exception_code)
  {
    memset (b_28, 32, 4);
  }

  /* Line: 100       : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100064;
#line 100 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 183 "shapes.c"
  memcpy (b_28, "BSED", 4);

  /* Line: 101       : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100065;
#line 101 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 190 "shapes.c"
  memcpy (b_15, "k1  ", 4);

  /* Line: 102       : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100066;
#line 102 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 197 "shapes.c"
  memcpy (b_15, "k2  ", 4);

  /* Line: 103       : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100067;
#line 103 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 204 "shapes.c"
  memcpy (b_29 + 78, "07", 2);

  /* Line: 104       : MOVE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100068;
#line 104 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_1);
#line 211 "shapes.c"
  memcpy (b_70 + 4 * 498, "L499", 4);

  /* Line: 105       : DISPLAY            : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x00100069;
#line 105 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_4);
#line 218 "shapes.c"
  cob_display (0, 1, 14, &c_2, COB_SET_FLD(f0, 4, b_16 + 6 * 1, &a_3), &c_3, &f_25, &c_3, COB_SET_DATA (f_75, cob_local_ptr + 16 + 2), &c_3, COB_SET_FLD(f1, 2, b_22 + 2 * 1, &a_5), &c_3, COB_SET_DATA (f_27, b_27), &c_3, COB_SET_DATA (f_28, b_28), &c_3, COB_SET_FLD(f2, 6, b_16 + 6 * (b_18 - 1), &a_6));

  /* Line: 107       : FREE               : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010006B;
#line 107 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_5);
#line 225 "shapes.c"
  cob_free_alloc (&b_28, NULL);

  /* Line: 108       : STOP RUN           : /work/cobol/examples/shapes.cob */
  module->module_stmt = 0x0010006C;
#line 108 "/work/cobol/examples/shapes.cob"
  cob_trace_stmt (st_6);
#line 232 "shapes.c"
  cob_stop_run (b_2);

  module->module_stmt = 0x0010006D;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Deallocate LOCAL storage */
  if (cob_local_ptr) {
  	cob_free (cob_local_ptr);
  	cob_local_ptr = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : /work/cobol/examples/shapes.cob */
  l_1:;
#line 0 "/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 261 "shapes.c"

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 1) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  shapes_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  b_27 = cob_external_addr ("WS_EXT", 10);
  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  b_18 = 1;
  /* initialize first record for WS-ENTRY */
  memset (b_16, 48, 4);
  memset (b_16 + 4, 32, 2);
  /* copy initialized record for WS-ENTRY to later occurrences */
  {
    cob_u8_ptr b_ptr = b_16;
    memcpy (b_ptr +      6, b_ptr,      6);	/* WS-ENTRY:      2 thru 2 */
    memcpy (b_ptr +     12, b_ptr,     12);	/* WS-ENTRY:      3 thru 4 */
    memcpy (b_ptr +     24, b_ptr,      6);	/* WS-ENTRY:      5 thru 5 */
  }
  memcpy (b_21, "03", 2);
  memset (b_22, 32, 18);
  cob_move ((cob_field *)&c_4, &f_25);
  memcpy (b_26, "ABC", 3);
  memcpy (b_29, "01", 2);
  memcpy (b_29 + 2, "02", 2);
  memcpy (b_29 + 4, "03", 2);
  memcpy (b_29 + 6, "04", 2);
  memcpy (b_29 + 8, "05", 2);
  memcpy (b_29 + 10, "06", 2);
  memcpy (b_29 + 12, "07", 2);
  memcpy (b_29 + 14, "08", 2);
  memcpy (b_29 + 16, "09", 2);
  memcpy (b_29 + 18, "10", 2);
  memset (b_29 + 20, 49, 2);
  memcpy (b_29 + 22, "12", 2);
  memcpy (b_29 + 24, "13", 2);
  memcpy (b_29 + 26, "14", 2);
  memcpy (b_29 + 28, "15", 2);
  memcpy (b_29 + 30, "16", 2);
  memcpy (b_29 + 32, "17", 2);
  memcpy (b_29 + 34, "18", 2);
  memcpy (b_29 + 36, "19", 2);
  memcpy (b_29 + 38, "20", 2);
  memcpy (b_29 + 40, "21", 2);
  memset (b_29 + 42, 50, 2);
  memcpy (b_29 + 44, "23", 2);
  memcpy (b_29 + 46, "24", 2);
  memcpy (b_29 + 48, "25", 2);
  memcpy (b_29 + 50, "26", 2);
  memcpy (b_29 + 52, "27", 2);
  memcpy (b_29 + 54, "28", 2);
  memcpy (b_29 + 56, "29", 2);
  memcpy (b_29 + 58, "30", 2);
  memcpy (b_29 + 60, "31", 2);
  memcpy (b_29 + 62, "32", 2);
  memset (b_29 + 64, 51, 2);
  memcpy (b_29 + 66, "34", 2);
  memcpy (b_29 + 68, "35", 2);
  memcpy (b_29 + 70, "36", 2);
  memcpy (b_29 + 72, "37", 2);
  memcpy (b_29 + 74, "38", 2);
  memcpy (b_29 + 76, "39", 2);
  memcpy (b_29 + 78, "40", 2);
  memset (b_70, 32, 2000);

  /* File initialization for REC-FILE */
  cob_file_malloc (&h_REC_FILE, NULL, 0, 0);
  h_REC_FILE->select_name = (const char *)"REC-FILE";
  h_REC_FILE->file_status = h_REC_FILE_status;
  memset (h_REC_FILE_status, '0', 2);
  h_REC_FILE->assign = (cob_field *)&c_5;
  h_REC_FILE->record = &f_15;
  h_REC_FILE->variable_record = NULL;
  h_REC_FILE->record_min = 0;
  h_REC_FILE->record_max = 24;
  h_REC_FILE->nkeys = 0;
  h_REC_FILE->keys = NULL;
  h_REC_FILE->file = NULL;
  h_REC_FILE->fd = -1;
  h_REC_FILE->organization = 1;
  h_REC_FILE->access_mode = 1;
  h_REC_FILE->lock_mode = 0;
  h_REC_FILE->open_mode = 0;
  h_REC_FILE->flag_optional = 0;
  h_REC_FILE->flag_line_adv = 0;
  h_REC_FILE->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump REC-FILE */
  cob_dump_file ("FD REC-FILE", h_REC_FILE);
  cob_dump_field_ext ( 0, "REC-FILE Record", &f_15, 0, 0);
  /* cob_dump_field_ext ( 1, "REC-A", COB_SET_FLD(f0, 24, b_15, &a_6), 0, 0); REDEFINES */
  /* cob_dump_field_ext ( 5, "REC-A-KEY", &f_9, 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-A-BODY", COB_SET_FLD(f0, 20, b_15 + 4, &a_5), 0, 0); */
  /* cob_dump_field_ext ( 1, "REC-B", COB_SET_FLD(f0, 24, b_15, &a_6), 0, 0); REDEFINES */
  /* cob_dump_field_ext ( 5, "REC-B-KEY", &f_12, 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-B-AMOUNT", COB_SET_FLD(f0, 8, b_15 + 4, &a_8), 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-B-FILL", COB_SET_FLD(f0, 12, b_15 + 12, &a_5), 0, 0); */

  /* Dump WORKING-STORAGE */
  cob_dump_output("WORKING-STORAGE");
  cob_dump_field_ext ( 1, "WS-TABLE", COB_SET_FLD(f0, 30, b_16, &a_6), 0, 0);
  cob_dump_field_ext ( 0, "WS-IX", &f_18, 0, 0);
  {
    int i_1;
    int max_1 = 5;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ENTRY", &f_17, 0, 1, i_1, 6UL); /* OCCURS 1 5 */
      cob_dump_field_ext (10, "WS-AMOUNT", &f_19, 0, 1, i_1, 6UL);
      cob_dump_field_ext (10, "WS-CODE", &f_20, 0, 1, i_1, 6UL);
    }
  }
  cob_dump_field_ext ( 1, "WS-COUNT", &f_21, 0, 0);
  cob_dump_field_ext ( 1, "WS-ODO-TABLE", COB_SET_FLD(f0, 2 * cob_get_numdisp (b_21, 2), b_22, &a_6), 0, 0);
  {
    int i_1;
    int max_1 = cob_get_numdisp (b_21, 2);
    if (max_1 > 9) max_1 = 9;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ROW", COB_SET_FLD(f0, 2, b_22, &a_6), 0, 1, i_1, 2UL); /* OCCURS 1 9 */
      cob_dump_field_ext (10, "WS-COL", &f_24, 0, 1, i_1, 2UL);
    }
  }
  cob_dump_field_ext ( 1, "WS-EDITED", &f_25, 0, 0);
  cob_dump_field_ext ( 1, "WS-A-VERY-LONG-DATA-NAME-OF-THIRTY-FIVE", COB_SET_FLD(f0, 3, b_26, &a_5), 0, 0);
  cob_dump_field_ext ( 1, "WS-EXT", COB_SET_DATA (f_27, b_27), 0, 0); /* EXTERNAL */
  /* Check BASED address for WS-BASED */
  if (b_28 == NULL)
  {
    cob_dump_field_ext ( 1, "WS-BASED", COB_SET_FLD(f0, 4, NULL, &a_5), 0, 0);
  }
  else
  {
    cob_dump_field_ext ( 1, "WS-BASED", COB_SET_DATA (f_28, b_28), 0, 0); /* BASED */
  }
  cob_dump_field_ext ( 1, "WS-FILLER-GROUP", COB_SET_FLD(f0, 80, b_29, &a_6), 0, 0);
  cob_dump_field_ext ( 5, "WS-F01", COB_SET_FLD(f0, 2, b_29, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F02", COB_SET_FLD(f0, 2, b_29 + 2, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F03", COB_SET_FLD(f0, 2, b_29 + 4, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F04", COB_SET_FLD(f0, 2, b_29 + 6, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F05", COB_SET_FLD(f0, 2, b_29 + 8, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F06", COB_SET_FLD(f0, 2, b_29 + 10, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F07", COB_SET_FLD(f0, 2, b_29 + 12, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F08", COB_SET_FLD(f0, 2, b_29 + 14, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F09", COB_SET_FLD(f0, 2, b_29 + 16, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F10", COB_SET_FLD(f0, 2, b_29 + 18, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F11", COB_SET_FLD(f0, 2, b_29 + 20, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F12", COB_SET_FLD(f0, 2, b_29 + 22, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F13", COB_SET_FLD(f0, 2, b_29 + 24, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F14", COB_SET_FLD(f0, 2, b_29 + 26, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F15", COB_SET_FLD(f0, 2, b_29 + 28, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F16", COB_SET_FLD(f0, 2, b_29 + 30, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F17", COB_SET_FLD(f0, 2, b_29 + 32, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F18", COB_SET_FLD(f0, 2, b_29 + 34, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F19", COB_SET_FLD(f0, 2, b_29 + 36, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F20", COB_SET_FLD(f0, 2, b_29 + 38, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F21", COB_SET_FLD(f0, 2, b_29 + 40, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F22", COB_SET_FLD(f0, 2, b_29 + 42, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F23", COB_SET_FLD(f0, 2, b_29 + 44, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F24", COB_SET_FLD(f0, 2, b_29 + 46, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F25", COB_SET_FLD(f0, 2, b_29 + 48, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F26", COB_SET_FLD(f0, 2, b_29 + 50, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F27", COB_SET_FLD(f0, 2, b_29 + 52, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F28", COB_SET_FLD(f0, 2, b_29 + 54, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F29", COB_SET_FLD(f0, 2, b_29 + 56, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F30", COB_SET_FLD(f0, 2, b_29 + 58, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F31", COB_SET_FLD(f0, 2, b_29 + 60, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F32", COB_SET_FLD(f0, 2, b_29 + 62, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F33", COB_SET_FLD(f0, 2, b_29 + 64, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F34", COB_SET_FLD(f0, 2, b_29 + 66, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F35", COB_SET_FLD(f0, 2, b_29 + 68, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F36", COB_SET_FLD(f0, 2, b_29 + 70, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F37", COB_SET_FLD(f0, 2, b_29 + 72, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F38", COB_SET_FLD(f0, 2, b_29 + 74, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F39", COB_SET_FLD(f0, 2, b_29 + 76, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F40", &f_69, 0, 0);
  cob_dump_field_ext ( 1, "WS-BIG", COB_SET_FLD(f0, 2000, b_70, &a_6), 0, 0);
  {
    int i_1;
    int max_1 = 500;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-LINE", &f_71, 0, 1, i_1, 4UL); /* OCCURS 1 500 */
    }
  }

  /* Dump LOCAL-STORAGE SECTION */
  cob_dump_output("LOCAL-STORAGE");
  cob_dump_field_ext ( 1, "LS-A", COB_SET_FLD(f0, 4, cob_local_ptr, &a_5), 0, 0);
  cob_dump_field_ext ( 1, "LS-G", COB_SET_FLD(f0, 5 + 3 * cob_get_numdisp (cob_local_ptr + 16 + 4, 1), cob_local_ptr + 16, &a_6), 0, 0);
  cob_dump_field_ext ( 5, "LS-G1", &f_74, 0, 0);
  cob_dump_field_ext ( 5, "LS-G2", &f_75, 0, 0);
  cob_dump_field_ext ( 5, "LS-COUNT", &f_76, 0, 0);
  {
    int i_1;
    int max_1 = cob_get_numdisp (cob_local_ptr + 16 + 4, 1);
    if (max_1 > 3) max_1 = 3;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "LS-TBL", &f_77, 0, 1, i_1, 3UL); /* OCCURS 1 3 */
    }
  }

  cob_dump_output("END OF DUMP - shapes");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  cob_close (h_REC_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_file_free (&h_REC_FILE,NULL);
  if (b_28) {
  	cob_free_alloc (&b_28, NULL);
  }
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'shapes' */

/* Initialize module structure for shapes */
static void shapes_module_init (cob_module *module)
{
  module->module_name = "shapes";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())shapes;
  module->module_cancel.funcptr = (void *(*)())shapes_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

