/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 19:47:11 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL -t /work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm /work/cobol/examples/shapes.cob */

/* Program local variables for 'shapes' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* EXTERNAL items */
static unsigned char	*b_27 = NULL;  /* WS-EXT */


/* File REC-FILE */
static cob_file		*h_REC_FILE = NULL;
static unsigned char	h_REC_FILE_status[4];

/* BASED WORKING-STORAGE SECTION */
static unsigned char	*b_28 = NULL; /* WS-BASED */


/* Local cob_field items */
cob_field		f0;
cob_field		f1;
cob_field		f2;


/* LOCAL storage pointer */
unsigned char		*cob_local_ptr = NULL;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_15[24] __attribute__((aligned));	/* REC-FILE Record */
static cob_u8_t	b_16[30] __attribute__((aligned));	/* WS-TABLE */
static int	b_18;	/* WS-IX */
static cob_u8_t	b_21[2] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_22[18] __attribute__((aligned));	/* WS-ODO-TABLE */
static cob_u8_t	b_25[9] __attribute__((aligned));	/* WS-EDITED */
static cob_u8_t	b_26[3] __attribute__((aligned));	/* WS-A-VERY-LONG-DATA-NAME-OF-THIRTY-FIVE */
static cob_u8_t	b_29[80] __attribute__((aligned));	/* WS-FILLER-GROUP */
static cob_u8_t	b_70[2000] __attribute__((aligned));	/* WS-BIG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_9	= {4, b_15, &a_5};	/* REC-A-KEY */
static cob_field f_12	= {4, b_15, &a_5};	/* REC-B-KEY */
static cob_field f_15	= {24, b_15, &a_5};	/* REC-FILE Record */
static cob_field f_17	= {6, b_16, &a_6};	/* WS-ENTRY */
static cob_field f_18	= {4, (cob_u8_t *)&b_18, &a_9};	/* WS-IX */
static cob_field f_19	= {4, b_16, &a_3};	/* WS-AMOUNT */
static cob_field f_20	= {2, b_16 + 4, &a_5};	/* WS-CODE */
static cob_field f_21	= {2, b_21, &a_10};	/* WS-COUNT */
static cob_field f_24	= {2, b_22, &a_5};	/* WS-COL */
static cob_field f_25	= {9, b_25, &a_4};	/* WS-EDITED */
static cob_field f_27	= {10, NULL, &a_5};	/* WS-EXT */
static cob_field f_28	= {4, NULL, &a_5};	/* WS-BASED */
static cob_field f_69	= {2, b_29 + 78, &a_10};	/* WS-F40 */
static cob_field f_71	= {4, b_70, &a_5};	/* WS-LINE */
static cob_field f_74	= {2, NULL, &a_5};	/* LS-G1 */
static cob_field f_75	= {2, NULL, &a_5};	/* LS-G2 */
static cob_field f_76	= {1, NULL, &a_11};	/* LS-COUNT */
static cob_field f_77	= {3, NULL, &a_5};	/* LS-TBL */

/* End of fields */

