/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 19:47:11 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL -t /work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm /work/cobol/examples/shapes.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'Z', 2},
	{',', 1},
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_3 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x24,   7,   2, 0x0000, p_1};
static const cob_field_attr a_5 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x10,   5,   1, 0x1000, NULL};
static const cob_field_attr a_8 =	{0x10,   8,   2, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_10 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x10,   1,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"4", &a_1};
static const cob_field c_2	= {7, (cob_u8_ptr)"SHAPES ", &a_2};
static const cob_field c_3	= {1, (cob_u8_ptr)" ", &a_2};
static const cob_field c_4	= {5, (cob_u8_ptr)"12345", &a_7};
static const cob_field c_5	= {10, (cob_u8_ptr)"shapes.dat", &a_2};


/* Strings */
static const char st_1[]	= "MOVE";
static const char st_2[]	= "SET";
static const char st_3[]	= "ALLOCATE";
static const char st_4[]	= "DISPLAY";
static const char st_5[]	= "FREE";
static const char st_6[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/work/cobol/examples/shapes.cob"};

static int COB_NOINLINE
cob_get_numdisp (const void *data, const int size)
{
	const unsigned char	*p;
	int			n;
	int 			retval;
	p = (const unsigned char *)data;
	retval = 0;
	for (n = 0; n < size; ++n, ++p) {
		retval *= 10;
		if (*p > '0' && *p <= '9')
		    retval += (*p - '0');
	}
	return retval;
}

