/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/calls/main.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */

/* Program local variables for 'CALLMAIN' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Call pointers */
static cob_call_union	call_CALLSUB;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[22] __attribute__((aligned));	/* WS-ARG-REC */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {22, b_17, &a_2};	/* WS-ARG-REC */
static cob_field f_20	= {4, b_17 + 8, &a_3};	/* WS-ARG-SUM */

/* End of fields */

