/* Generated by           cobc 3.2.0 */
/* Generated from         /work/cobol/examples/calls/sub.cob */
/* Generated at           Sep 19 2026 14:46:06 */
/* GnuCOBOL build date    Feb 06 2026 20:18:39 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -x -A -O0 -gdwarf-4 -o /work/cobol/build/calls/calls -g -fdump=ALL --save-temps -t /work/cobol/build/calls/calls.lst -ftsymbols /work/cobol/examples/calls/main.cob /work/cobol/examples/calls/sub.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   9,   0, 0x0821, NULL};
static const cob_field_attr a_3 =	{0x1b,   9,   0, 0x0041, NULL};
static const cob_field_attr a_4 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x01,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {1, (cob_u8_ptr)"0", &a_1};


/* Strings */
static const char st_1[]	= "0000-SUB-MAIN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/work/cobol/examples/calls/sub.cob"};

#define cob_nop	if (!module) cob_nop

