import { describe, it, expect } from 'vitest';
import {
  SourceFileRegistry,
  demangleProgramId,
  parseProcedureMap,
  splitLines,
  splitProgramSegments
} from '../../../src/manifest/index.js';

const TWO_PROGRAMS = [
  '/* Generated by           cobc 3.2.0 */',
  '#define  COB_SOURCE_FILE\t\t"C:/work/outer.cob"',
  'static int\t\tOUTER ();',
  'static int\t\tOUTER_ (const int);',
  'int',
  'main (int argc, char **argv)',
  '{',
  '  cob_stop_run (OUTER ());',
  '}',
  "/* PROGRAM-ID 'OUTER' */",
  "/* ENTRY 'OUTER' */",
  'static int',
  'OUTER ()',
  '{',
  '  return OUTER_ (0);',
  '}',
  'static int',
  'OUTER_ (const int entry)',
  '{',
  '  /* Line: 10        : Entry     OUTER                   : C:/work/outer.cob */',
  '#line 10 "C:/work/outer.cob"',
  '  ENTRY_OUTER:\tmodule->statement = STMT_ENTRY;',
  '#line 23 "outer.c"',
  '  /* Line: 11        : Section   MAIN-SEC                : C:/work/outer.cob */',
  '#line 11 "C:/work/outer.cob"',
  '  SECTION_MAIN__SEC_l_3:\tmodule->statement = STMT_ENTRY;',
  '#line 27 "outer.c"',
  '  /* Line: 12        : Paragraph P-ONE                   : C:/work/outer.cob */',
  '  l_4:;',
  '#line 12 "C:/work/outer.cob"',
  '  PARAGRAPH_P__ONE_l_4:\tmodule->statement = STMT_ENTRY;',
  '#line 32 "outer.c"',
  '  /* Line: 13        : DISPLAY            : C:/work/outer.cob */',
  '#line 13 "C:/work/outer.cob"',
  '  module->statement = STMT_DISPLAY;',
  '#line 36 "outer.c"',
  '  cob_display (0, 1, 1, &c_1);',
  '  /* Line: 1         : Paragraph P-COPY                  : C:\\work\\inc\\para.cpy */',
  '#line 1 "C:\\\\work\\\\inc\\\\para.cpy"',
  '  PARAGRAPH_P__COPY_l_5:\tmodule->statement = STMT_ENTRY;',
  '#line 41 "outer.c"',
  '  /* Line: 2         : DISPLAY            : C:\\work\\inc\\para.cpy */',
  '#line 2 "C:\\\\work\\\\inc\\\\para.cpy"',
  '  module->statement = STMT_DISPLAY;',
  '#line 45 "outer.c"',
  '  /* Line: 20        : Section   LAST-SEC                : C:/work/outer.cob */',
  '#line 20 "C:/work/outer.cob"',
  '  SECTION_LAST__SEC_l_6:\tmodule->statement = STMT_ENTRY;',
  '#line 49 "outer.c"',
  '  /* Line: 21        : Paragraph P-TWO                   : C:/work/outer.cob */',
  '#line 21 "C:/work/outer.cob"',
  '  PARAGRAPH_P__TWO_l_7:\tmodule->statement = STMT_ENTRY;',
  '#line 53 "outer.c"',
  '  /* Line: 22        : STOP RUN           : C:/work/outer.cob */',
  '#line 22 "C:/work/outer.cob"',
  '  module->statement = STMT_STOP_RUN;',
  '#line 57 "outer.c"',
  '  /* Line: 23        : last source line                  :C:/work/outer.cob */',
  '#line 23 "C:/work/outer.cob"',
  '  module->module_stmt = 0x00100032;',
  '#line 61 "outer.c"',
  '  cob_nop ();',
  '  P_dump:',
  '  cob_dump_output ("END OF DUMP - OUTER");',
  '}',
  "/* End PROGRAM-ID 'OUTER' */",
  'static void OUTER_module_init (cob_module *module)',
  '{',
  '  module->flag_main = 1;',
  '}',
  "/* PROGRAM-ID 'INNER-ONE' */",
  "/* ENTRY 'INNER-ONE' */",
  'static int',
  'INNER__ONE (cob_u8_t *b_9)',
  '{',
  '  return INNER__ONE_ (0, b_9);',
  '}',
  'static int',
  'INNER__ONE_ (const int entry, cob_u8_t *b_9)',
  '{',
  '  /* Line: 30        : Entry     INNER-ONE               : C:/work/outer.cob */',
  '#line 30 "C:/work/outer.cob"',
  '  ENTRY_INNER__ONE:\tmodule->statement = STMT_ENTRY;',
  '#line 83 "outer.c"',
  '  /* Line: 31        : Paragraph P-IN                    : C:/work/outer.cob */',
  '#line 31 "C:/work/outer.cob"',
  '  cob_nop ();',
  '#line 87 "outer.c"',
  '}',
  "/* End PROGRAM-ID 'INNER-ONE' */",
  'static void INNER__ONE_module_init (cob_module *module)',
  '{',
  '  module->flag_main = 0;',
  '}'
].join('\n');

describe('splitProgramSegments', () => {
  it('brackets every PROGRAM-ID with its identity', () => {
    const { segments, diagnostics } = splitProgramSegments(splitLines(TWO_PROGRAMS));
    expect(diagnostics).toEqual([]);
    expect(segments.map((s) => [s.programId, s.cFunction, s.cEntry, s.isMain, s.kind])).toEqual([
      ['OUTER', 'OUTER_', 'OUTER', true, 'program'],
      ['INNER-ONE', 'INNER__ONE_', 'INNER__ONE', false, 'program']
    ]);
    expect(segments[0].startLine).toBe(10);
    expect(segments[0].lines[0]).toContain("PROGRAM-ID 'OUTER'");
    expect(segments[0].lines[segments[0].lines.length - 1]).toContain("End PROGRAM-ID 'OUTER'");
    expect(segments[1].endLine).toBe(TWO_PROGRAMS.split('\n').length - 4);
  });

  it('falls back to one whole-file segment named from the dump when markers are missing', () => {
    const text = ['static int', 'HELLO_ (const int entry)', '{', '  cob_dump_output("END OF DUMP - HELLO");', '}'].join('\n');
    const { segments, diagnostics } = splitProgramSegments(splitLines(text));
    expect(segments).toHaveLength(1);
    expect(segments[0]).toMatchObject({ programId: 'HELLO', cFunction: 'HELLO_', cEntry: 'HELLO', startLine: 1, endLine: 5 });
    expect(diagnostics.map((d) => d.message)).toEqual([expect.stringContaining('no PROGRAM-ID markers')]);
  });

  it('demangles cobc program ids', () => {
    expect(demangleProgramId('INNER__ONE_')).toBe('INNER-ONE');
    expect(demangleProgramId('A_2EB')).toBe('A.B');
  });
});

describe('parseProcedureMap', () => {
  const registry = new SourceFileRegistry();
  const { segments } = splitProgramSegments(splitLines(TWO_PROGRAMS));
  const outer = parseProcedureMap(segments[0], 'C:/build/outer.c', registry, 'C:/work/outer.cob');
  const inner = parseProcedureMap(segments[1], 'C:/build/outer.c', registry, 'C:/work/outer.cob');

  it('interns sources once, unescaping #line paths', () => {
    expect(registry.sources.map((s) => s.path)).toEqual(['C:/work/outer.cob', 'C:\\work\\inc\\para.cpy']);
    expect(outer.sourceFileId).toBe(0);
    expect(inner.sourceFileId).toBe(0);
    expect(outer.diagnostics).toEqual([]);
  });

  it('keeps only COBOL rows in the line map with the span each governs', () => {
    expect(outer.lineMap.slice(0, 3)).toEqual([
      { cLine: 22, endCLine: 22, sourceFileId: 0, line: 10 },
      { cLine: 26, endCLine: 26, sourceFileId: 0, line: 11 },
      { cLine: 31, endCLine: 31, sourceFileId: 0, line: 12 }
    ]);
    expect(outer.lineMap.find((r) => r.line === 1)).toEqual({ cLine: 40, endCLine: 40, sourceFileId: 1, line: 1 });
    expect(outer.lineMap.some((r) => r.sourceFileId !== 0 && r.sourceFileId !== 1)).toBe(false);
    expect(inner.lineMap.map((r) => r.line)).toEqual([30, 31]);
  });

  it('builds sections and paragraphs with end lines from the next start', () => {
    expect(outer.sections).toEqual([
      { name: 'MAIN-SEC', kind: 'section', sourceFileId: 0, startLine: 11, endLine: 19, cLabel: 'SECTION_MAIN__SEC_l_3' },
      { name: 'LAST-SEC', kind: 'section', sourceFileId: 0, startLine: 20, endLine: 22, cLabel: 'SECTION_LAST__SEC_l_6' }
    ]);
    expect(outer.paragraphs).toEqual([
      { name: 'P-ONE', kind: 'paragraph', sectionName: 'MAIN-SEC', sourceFileId: 0, startLine: 12, endLine: 19, cLabel: 'PARAGRAPH_P__ONE_l_4' },
      { name: 'P-COPY', kind: 'paragraph', sectionName: 'MAIN-SEC', sourceFileId: 1, startLine: 1, endLine: 2, cLabel: 'PARAGRAPH_P__COPY_l_5' },
      { name: 'P-TWO', kind: 'paragraph', sectionName: 'LAST-SEC', sourceFileId: 0, startLine: 21, endLine: 22, cLabel: 'PARAGRAPH_P__TWO_l_7' }
    ]);
    expect(outer.procedureDivisionLine).toBe(11);
  });

  it('handles the 3.1.2 shape without labels', () => {
    expect(inner.paragraphs).toEqual([{ name: 'P-IN', kind: 'paragraph', sourceFileId: 0, startLine: 31, endLine: 31 }]);
    expect(inner.procedureDivisionLine).toBe(31);
  });

  it('attributes a body without COBOL directives to the fallback source', () => {
    const fresh = new SourceFileRegistry();
    const text = ["/* PROGRAM-ID 'EMPTY' */", 'static int', 'EMPTY_ (const int entry)', '{', '}', "/* End PROGRAM-ID 'EMPTY' */"].join('\n');
    const { segments: empty } = splitProgramSegments(splitLines(text));
    const map = parseProcedureMap(empty[0], '/b/empty.c', fresh, '/src/empty.cob');
    expect(fresh.sources).toEqual([{ id: 0, path: '/src/empty.cob', kind: 'copybook' }]);
    expect(map).toMatchObject({ sourceFileId: 0, lineMap: [], sections: [], paragraphs: [] });
    expect(map.procedureDivisionLine).toBeUndefined();
  });
});
