/* Generated by           cobc 3.1.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:58:58 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   5,   5, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   5,  -2, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   5,   5, 0x0007, NULL};
static const cob_field_attr a_4 =	{0x10,   5,  -2, 0x0003, NULL};
static const cob_field_attr a_5 =	{0x12,   5,   5, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x12,   5,  -2, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x11,   5,   5, 0x0820, NULL};
static const cob_field_attr a_8 =	{0x11,   5,  -2, 0x0820, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Strings */
static const char st_1[]	= "DISPLAY";
static const char st_2[]	= "GOBACK";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"../scaling.cob"};
