/* Generated by           cobc 3.1.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:58:58 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"../scaling.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 20 2026 22:58:58"
#define  COB_MODULE_DATE		20260920
#define  COB_MODULE_TIME		225858

/* Global variables */
#include "scaling.c.h"

/* Function prototypes */

int		SCALING (void);
static int		SCALING_ (const int);
static void		SCALING_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'SCALING' */

/* ENTRY 'SCALING' */

int
SCALING ()
{
  return SCALING_ (0);
}

static int
SCALING_ (const int entry)
{
  /* Program local variables */
  #include "scaling.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 14        : Entry     SCALING                 : ../scaling.cob */
  l_2:;
#line 14 "../scaling.cob"
  ENTRY_SCALING:;
#line 92 "scaling.c"
#line 15 "../scaling.cob"
  SECTION_MAIN_20SECTION:;
#line 95 "scaling.c"
#line 15 "../scaling.cob"
  cob_nop ();
#line 98 "scaling.c"

  /* Line: 15        : DISPLAY            : ../scaling.cob */
  module->module_stmt = 0x0010000F;
#line 15 "../scaling.cob"
  cob_trace_stmt (st_1);
#line 104 "scaling.c"
  cob_display (0, 1, 8, &f_8, &f_9, &f_10, &f_11, &f_12, &f_13, &f_14, &f_15);

  /* Line: 17        : GOBACK             : ../scaling.cob */
  module->module_stmt = 0x00100011;
#line 17 "../scaling.cob"
  cob_trace_stmt (st_2);
#line 111 "scaling.c"
  goto exit_program;

  module->module_stmt = 0x00100012;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  SCALING_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memset (b_8, 48, 3);
  memset (b_9, 48, 3);
  cob_move (&cob_all_zero, &f_10);
  cob_move (&cob_all_zero, &f_11);
  cob_set_packed_zero (&f_12);
  cob_set_packed_zero (&f_13);
  memset (b_14, 0, 2);
  memset (b_15, 0, 2);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output("WORKING-STORAGE");
    cob_dump_field_ext ( 1, "LEAD-D", &f_8, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-D", &f_9, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-S", &f_10, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-S", &f_11, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-P", &f_12, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-P", &f_13, 0, 0);
    cob_dump_field_ext ( 1, "LEAD-B", &f_14, 0, 0);
    cob_dump_field_ext ( 1, "TRAIL-B", &f_15, 0, 0);

  }
  cob_dump_output("END OF DUMP - SCALING");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'SCALING' */

/* Initialize module structure for SCALING */
static void SCALING_module_init (cob_module *module)
{
  module->module_name = "SCALING";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())SCALING;
  module->module_cancel.funcptr = (void *(*)())SCALING_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

