/* Generated by           cobc 3.1.2.0 */
/* Generated from         ../scaling.cob */
/* Generated at           Sep 20 2026 22:58:58 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C -g -fdump=ALL --save-temps -t scaling.lst -ftsymbols -o scaling.c ../scaling.cob */

/* Program local variables for 'SCALING' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[3] __attribute__((aligned));	/* LEAD-D */
static cob_u8_t	b_9[3] __attribute__((aligned));	/* TRAIL-D */
static cob_u8_t	b_10[4] __attribute__((aligned));	/* LEAD-S */
static cob_u8_t	b_11[4] __attribute__((aligned));	/* TRAIL-S */
static cob_u8_t	b_12[2] __attribute__((aligned));	/* LEAD-P */
static cob_u8_t	b_13[2] __attribute__((aligned));	/* TRAIL-P */
static cob_u8_t	b_14[2] __attribute__((aligned));	/* LEAD-B */
static cob_u8_t	b_15[2] __attribute__((aligned));	/* TRAIL-B */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {3, b_8, &a_1};	/* LEAD-D */
static cob_field f_9	= {3, b_9, &a_2};	/* TRAIL-D */
static cob_field f_10	= {4, b_10, &a_3};	/* LEAD-S */
static cob_field f_11	= {4, b_11, &a_4};	/* TRAIL-S */
static cob_field f_12	= {2, b_12, &a_5};	/* LEAD-P */
static cob_field f_13	= {2, b_13, &a_6};	/* TRAIL-P */
static cob_field f_14	= {2, b_14, &a_7};	/* LEAD-B */
static cob_field f_15	= {2, b_15, &a_8};	/* TRAIL-B */

/* End of fields */

