/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 15:47:09 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -C -g -fdump=ALL -t C:/work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm C:/work/cobol/examples/shapes.cob */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:/work/cobol/examples/shapes.cob"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 15:47:09"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		154709

/* Global variables */
#include "shapes.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		shapes (void);
static int		shapes_ (const int);
static void		shapes_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'shapes' */

/* ENTRY 'shapes' */

int
shapes ()
{
  return shapes_ (0);
}

static int
shapes_ (const int entry)
{
  /* Program local variables */
  #include "shapes.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  module->frame_ptr = frame_stack;

  /* Allocate LOCAL storage */
  cob_local_ptr = cob_malloc (32U);

  /* Initialize LOCAL storage */
  /* initialize field LS-A */
#line 82 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 87 "shapes.c"
  memset (cob_local_ptr, 0x0, 4);

  /* initialize field LS-G1 */
#line 84 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 93 "shapes.c"
  memset (cob_local_ptr + 16, 0x0, 4);
  /* initialize field LS-COUNT */
#line 86 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 98 "shapes.c"
  *(cob_local_ptr + 16 + 4) = 50;
  /* initialize field LS-TBL */
#line 87 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 103 "shapes.c"
  memset (cob_local_ptr + 16 + 5, 0x0, 9);


  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  module->frame_ptr->section_name = "";
  module->frame_ptr->paragraph_name = "shapes";
  module->frame_ptr->module_stmt = 0x0010005A;
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 90        : Entry     shapes                  : C:/work/cobol/examples/shapes.cob */
  l_2:;
#line 90 "C:/work/cobol/examples/shapes.cob"
  ENTRY_SHAPES:	module->statement = STMT_ENTRY;
#line 128 "shapes.c"
  module->module_stmt = 0x0010005A;
  module->section_name = NULL;
  module->paragraph_name = NULL;

  /* Line: 90        : Paragraph 0000-MAIN               : C:/work/cobol/examples/shapes.cob */
#line 90 "C:/work/cobol/examples/shapes.cob"
  PARAGRAPH_0000__MAIN_l_4:	module->statement = STMT_ENTRY;
#line 136 "shapes.c"
  module->paragraph_name = st_1;

  /* Line: 91        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 91 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 142 "shapes.c"
  module->module_stmt = 0x0010005B;
  memcpy (b_25 + 6LL * 1LL, "1234", 4);

  /* Line: 92        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 92 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 149 "shapes.c"
  module->module_stmt = 0x0010005C;
  memcpy (b_25 + 4 + 6LL * 1LL, "AB", 2);

  /* Line: 93        : SET                : C:/work/cobol/examples/shapes.cob */
#line 93 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_SET;
#line 156 "shapes.c"
  module->module_stmt = 0x0010005D;
  b_27 = 3;

  /* Line: 94        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 94 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 163 "shapes.c"
  module->module_stmt = 0x0010005E;
  memcpy (b_31 + 2LL * 1LL, "XY", 2);

  /* Line: 95        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 95 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 170 "shapes.c"
  module->module_stmt = 0x0010005F;
  memcpy (cob_local_ptr + 16, "AB", 2);

  /* Line: 96        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 96 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 177 "shapes.c"
  module->module_stmt = 0x00100060;
  memcpy (cob_local_ptr + 16 + 2, "CD", 2);

  /* Line: 97        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 97 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 184 "shapes.c"
  module->module_stmt = 0x00100061;
  memset (cob_local_ptr + 16 + 5 + 3LL * 1LL, 81, 3);

  /* Line: 98        : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 98 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 191 "shapes.c"
  module->module_stmt = 0x00100062;
  memcpy (b_36, "external! ", 10);

  /* Line: 99        : ALLOCATE           : C:/work/cobol/examples/shapes.cob */
#line 99 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_ALLOCATE;
#line 198 "shapes.c"
  module->module_stmt = 0x00100063;
  cob_glob_ptr->cob_exception_code = 0;
  cob_allocate (&b_37, NULL, (cob_field *)&c_1, NULL);
  if (!cob_glob_ptr->cob_exception_code)
  {
    memset (b_37, (unsigned char)' ', 4);
  }

  /* Line: 100       : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 100 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 210 "shapes.c"
  module->module_stmt = 0x00100064;
  memcpy (b_37, "BSED", 4);

  /* Line: 101       : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 101 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 217 "shapes.c"
  module->module_stmt = 0x00100065;
  memcpy (b_24, "k1  ", 4);

  /* Line: 102       : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 102 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 224 "shapes.c"
  module->module_stmt = 0x00100066;
  memcpy (b_24, "k2  ", 4);

  /* Line: 103       : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 103 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 231 "shapes.c"
  module->module_stmt = 0x00100067;
  memcpy (b_38 + 78, "07", 2);

  /* Line: 104       : MOVE               : C:/work/cobol/examples/shapes.cob */
#line 104 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_MOVE;
#line 238 "shapes.c"
  module->module_stmt = 0x00100068;
  memcpy (b_79 + 4LL * 498LL, "L499", 4);

  /* Line: 105       : DISPLAY            : C:/work/cobol/examples/shapes.cob */
#line 105 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_DISPLAY;
#line 245 "shapes.c"
  module->module_stmt = 0x00100069;
  cob_display (0, 1, 14, &c_2, COB_SET_FLD (f0, 4, b_25 + 6LL * 1LL, &a_3), &c_3, &f_34, &c_3, COB_SET_DATA (f_84, cob_local_ptr + 16 + 2), &c_3, COB_SET_FLD (f1, 2, b_31 + 2LL * 1LL, &a_5), &c_3, COB_SET_DATA (f_36, b_36), &c_3, COB_SET_DATA (f_37, b_37), &c_3, COB_SET_FLD (f2, 6, b_25 + 6LL * ((cob_s64_t)(b_27) - 1), &a_6));

  /* Line: 107       : FREE               : C:/work/cobol/examples/shapes.cob */
#line 107 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_FREE;
#line 252 "shapes.c"
  module->module_stmt = 0x0010006B;
  cob_free_alloc (&b_37, NULL);

  /* Line: 108       : STOP RUN           : C:/work/cobol/examples/shapes.cob */
#line 108 "C:/work/cobol/examples/shapes.cob"
  module->statement = STMT_STOP_RUN;
#line 259 "shapes.c"
  module->module_stmt = 0x0010006C;
  cob_stop_run (b_2);

  /* Line: 109       : last source line                  :C:/work/cobol/examples/shapes.cob */
#line 109 "C:/work/cobol/examples/shapes.cob"
  module->module_stmt = 0x0010006D;
#line 266 "shapes.c"
  cob_nop ();


  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Deallocate LOCAL storage */
  if (cob_local_ptr) {
  	cob_free (cob_local_ptr);
  	cob_local_ptr = NULL;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : C:/work/cobol/examples/shapes.cob */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS))
  	cob_fatal_error (COB_FERROR_FILE);

  /* Implicit Default Error Handler return */
  for (temp_index = frame_ptr; temp_index->perform_through; temp_index--) {
    if (temp_index->perform_through == 1) {
      frame_ptr = temp_index;
      goto *frame_ptr->return_address_ptr;
    }
  }

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  shapes_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  b_36 = cob_external_addr ("WS_EXT", 10);
  /* Initialize WORKING-STORAGE, Default byte: 0x00 */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-IX */
#line 26 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 344 "shapes.c"
  memset ((cob_u8_t *)&b_27, 0x0, 4);

  /* initialize field WS-TABLE */
#line 25 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 350 "shapes.c"
  memset (b_25, 0x0, 30);

  /* initialize field WS-COUNT */
#line 29 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 356 "shapes.c"
  memcpy (b_30, "03", 2);

  /* initialize field WS-ODO-TABLE */
#line 30 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 362 "shapes.c"
  memset (b_31, 0x0, 18);

  /* initialize field WS-EDITED */
#line 33 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 368 "shapes.c"
  cob_move ((cob_field *)&c_4, &f_34);

  /* initialize field WS-A-VERY-LONG-DATA-NAME-OF-THIRTY-FIVE */
#line 34 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 374 "shapes.c"
  memcpy (b_35, "ABC", 3);

  /* initialize field WS-F01 */
#line 39 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 380 "shapes.c"
  memcpy (b_38, "01", 2);
  /* initialize field WS-F02 */
#line 40 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 385 "shapes.c"
  memcpy (b_38 + 2, "02", 2);
  /* initialize field WS-F03 */
#line 41 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 390 "shapes.c"
  memcpy (b_38 + 4, "03", 2);
  /* initialize field WS-F04 */
#line 42 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 395 "shapes.c"
  memcpy (b_38 + 6, "04", 2);
  /* initialize field WS-F05 */
#line 43 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 400 "shapes.c"
  memcpy (b_38 + 8, "05", 2);
  /* initialize field WS-F06 */
#line 44 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 405 "shapes.c"
  memcpy (b_38 + 10, "06", 2);
  /* initialize field WS-F07 */
#line 45 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 410 "shapes.c"
  memcpy (b_38 + 12, "07", 2);
  /* initialize field WS-F08 */
#line 46 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 415 "shapes.c"
  memcpy (b_38 + 14, "08", 2);
  /* initialize field WS-F09 */
#line 47 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 420 "shapes.c"
  memcpy (b_38 + 16, "09", 2);
  /* initialize field WS-F10 */
#line 48 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 425 "shapes.c"
  memcpy (b_38 + 18, "10", 2);
  /* initialize field WS-F11 */
#line 49 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 430 "shapes.c"
  memset (b_38 + 20, 49, 2);
  /* initialize field WS-F12 */
#line 50 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 435 "shapes.c"
  memcpy (b_38 + 22, "12", 2);
  /* initialize field WS-F13 */
#line 51 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 440 "shapes.c"
  memcpy (b_38 + 24, "13", 2);
  /* initialize field WS-F14 */
#line 52 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 445 "shapes.c"
  memcpy (b_38 + 26, "14", 2);
  /* initialize field WS-F15 */
#line 53 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 450 "shapes.c"
  memcpy (b_38 + 28, "15", 2);
  /* initialize field WS-F16 */
#line 54 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 455 "shapes.c"
  memcpy (b_38 + 30, "16", 2);
  /* initialize field WS-F17 */
#line 55 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 460 "shapes.c"
  memcpy (b_38 + 32, "17", 2);
  /* initialize field WS-F18 */
#line 56 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 465 "shapes.c"
  memcpy (b_38 + 34, "18", 2);
  /* initialize field WS-F19 */
#line 57 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 470 "shapes.c"
  memcpy (b_38 + 36, "19", 2);
  /* initialize field WS-F20 */
#line 58 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 475 "shapes.c"
  memcpy (b_38 + 38, "20", 2);
  /* initialize field WS-F21 */
#line 59 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 480 "shapes.c"
  memcpy (b_38 + 40, "21", 2);
  /* initialize field WS-F22 */
#line 60 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 485 "shapes.c"
  memset (b_38 + 42, 50, 2);
  /* initialize field WS-F23 */
#line 61 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 490 "shapes.c"
  memcpy (b_38 + 44, "23", 2);
  /* initialize field WS-F24 */
#line 62 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 495 "shapes.c"
  memcpy (b_38 + 46, "24", 2);
  /* initialize field WS-F25 */
#line 63 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 500 "shapes.c"
  memcpy (b_38 + 48, "25", 2);
  /* initialize field WS-F26 */
#line 64 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 505 "shapes.c"
  memcpy (b_38 + 50, "26", 2);
  /* initialize field WS-F27 */
#line 65 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 510 "shapes.c"
  memcpy (b_38 + 52, "27", 2);
  /* initialize field WS-F28 */
#line 66 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 515 "shapes.c"
  memcpy (b_38 + 54, "28", 2);
  /* initialize field WS-F29 */
#line 67 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 520 "shapes.c"
  memcpy (b_38 + 56, "29", 2);
  /* initialize field WS-F30 */
#line 68 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 525 "shapes.c"
  memcpy (b_38 + 58, "30", 2);
  /* initialize field WS-F31 */
#line 69 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 530 "shapes.c"
  memcpy (b_38 + 60, "31", 2);
  /* initialize field WS-F32 */
#line 70 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 535 "shapes.c"
  memcpy (b_38 + 62, "32", 2);
  /* initialize field WS-F33 */
#line 71 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 540 "shapes.c"
  memset (b_38 + 64, 51, 2);
  /* initialize field WS-F34 */
#line 72 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 545 "shapes.c"
  memcpy (b_38 + 66, "34", 2);
  /* initialize field WS-F35 */
#line 73 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 550 "shapes.c"
  memcpy (b_38 + 68, "35", 2);
  /* initialize field WS-F36 */
#line 74 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 555 "shapes.c"
  memcpy (b_38 + 70, "36", 2);
  /* initialize field WS-F37 */
#line 75 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 560 "shapes.c"
  memcpy (b_38 + 72, "37", 2);
  /* initialize field WS-F38 */
#line 76 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 565 "shapes.c"
  memcpy (b_38 + 74, "38", 2);
  /* initialize field WS-F39 */
#line 77 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 570 "shapes.c"
  memcpy (b_38 + 76, "39", 2);
  /* initialize field WS-F40 */
#line 78 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 575 "shapes.c"
  memcpy (b_38 + 78, "40", 2);

  /* initialize field WS-BIG */
#line 79 "C:/work/cobol/examples/shapes.cob"
  cob_nop ();
#line 581 "shapes.c"
  memset (b_79, 0x0, 2000);


  /* File initialization for REC-FILE */
  cob_file_malloc (&h_REC_FILE, NULL, 0, 0);
  h_REC_FILE->select_name = (const char *)"REC-FILE";
  h_REC_FILE->file_status = h_REC_FILE_status;
  memset (h_REC_FILE_status, '0', 2);
  h_REC_FILE->assign = (cob_field *)&c_5;
  h_REC_FILE->record = &f_24;
  h_REC_FILE->variable_record = NULL;
  h_REC_FILE->record_min = 0;
  h_REC_FILE->record_max = 24;
  h_REC_FILE->file = NULL;
  h_REC_FILE->organization = 1;
  h_REC_FILE->access_mode = 1;
  h_REC_FILE->lock_mode = 0;
  h_REC_FILE->open_mode = 0;
  h_REC_FILE->flag_optional = 0;
  h_REC_FILE->flag_line_adv = 0;
  h_REC_FILE->flag_select_features = 0;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  /* Dump REC-FILE */
  cob_dump_file ("FD REC-FILE", h_REC_FILE);
  cob_dump_field_ext ( 0, "REC-FILE Record", &f_24, 0, 0);
  /* cob_dump_field_ext ( 1, "REC-A", COB_SET_FLD (f0, 24, b_24, &a_6), 0, 0); REDEFINES */
  /* cob_dump_field_ext ( 5, "REC-A-KEY", &f_18, 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-A-BODY", COB_SET_FLD (f0, 20, b_24 + 4, &a_5), 0, 0); */
  /* cob_dump_field_ext ( 1, "REC-B", COB_SET_FLD (f0, 24, b_24, &a_6), 0, 0); REDEFINES */
  /* cob_dump_field_ext ( 5, "REC-B-KEY", &f_21, 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-B-AMOUNT", COB_SET_FLD (f0, 8, b_24 + 4, &a_8), 0, 0); */
  /* cob_dump_field_ext ( 5, "REC-B-FILL", COB_SET_FLD (f0, 12, b_24 + 12, &a_5), 0, 0); */

  /* Dump WORKING-STORAGE */
  cob_dump_output ("WORKING-STORAGE");
  cob_dump_field_ext (77, "RETURN-CODE", COB_SET_FLD (f0, 4, (cob_u8_t *)&b_2, &a_9), 0, 0);
  cob_dump_field_ext ( 1, "WS-TABLE", COB_SET_FLD (f0, 30, b_25, &a_6), 0, 0);
  cob_dump_field_ext ( 0, "WS-IX", &f_27, 0, 0);
  {
    int i_1;
    int max_1 = 5;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ENTRY", &f_26, 0, 1, i_1, 6UL); /* OCCURS 1 5 */
      cob_dump_field_ext (10, "WS-AMOUNT", &f_28, 0, 1, i_1, 6UL);
      cob_dump_field_ext (10, "WS-CODE", &f_29, 0, 1, i_1, 6UL);
    }
  }
  cob_dump_field_ext ( 1, "WS-COUNT", &f_30, 0, 0);
  cob_dump_field_ext ( 1, "WS-ODO-TABLE", COB_SET_FLD (f0, (2*cob_get_numdisp (b_30, 2)), b_31, &a_6), 0, 0);
  {
    int i_1;
    int max_1 = cob_get_numdisp (b_30, 2);
    if (max_1 > 9) max_1 = 9;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-ROW", COB_SET_FLD (f0, 2, b_31, &a_6), 0, 1, i_1, 2UL); /* OCCURS 1 9 */
      cob_dump_field_ext (10, "WS-COL", &f_33, 0, 1, i_1, (cob_uli_t)(2));
    }
  }
  cob_dump_field_ext ( 1, "WS-EDITED", &f_34, 0, 0);
  cob_dump_field_ext ( 1, "WS-A-VERY-LONG-DATA-NAME-OF-THIRTY-FIVE", COB_SET_FLD (f0, 3, b_35, &a_5), 0, 0);
  cob_dump_field_ext ( 1, "WS-EXT", COB_SET_DATA (f_36, b_36), 0, 0); /* EXTERNAL */
  /* Check BASED address for WS-BASED */
  if (b_37 == NULL)
  {
    cob_dump_field_ext ( 1, "WS-BASED", COB_SET_FLD (f0, 4, NULL, &a_5), 0, 0);
  }
  else
  {
    cob_dump_field_ext ( 1, "WS-BASED", COB_SET_DATA (f_37, b_37), 0, 0); /* BASED */
  }
  cob_dump_field_ext ( 1, "WS-FILLER-GROUP", COB_SET_FLD (f0, 80, b_38, &a_6), 0, 0);
  cob_dump_field_ext ( 5, "WS-F01", COB_SET_FLD (f0, 2, b_38, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F02", COB_SET_FLD (f0, 2, b_38 + 2, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F03", COB_SET_FLD (f0, 2, b_38 + 4, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F04", COB_SET_FLD (f0, 2, b_38 + 6, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F05", COB_SET_FLD (f0, 2, b_38 + 8, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F06", COB_SET_FLD (f0, 2, b_38 + 10, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F07", COB_SET_FLD (f0, 2, b_38 + 12, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F08", COB_SET_FLD (f0, 2, b_38 + 14, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F09", COB_SET_FLD (f0, 2, b_38 + 16, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F10", COB_SET_FLD (f0, 2, b_38 + 18, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F11", COB_SET_FLD (f0, 2, b_38 + 20, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F12", COB_SET_FLD (f0, 2, b_38 + 22, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F13", COB_SET_FLD (f0, 2, b_38 + 24, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F14", COB_SET_FLD (f0, 2, b_38 + 26, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F15", COB_SET_FLD (f0, 2, b_38 + 28, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F16", COB_SET_FLD (f0, 2, b_38 + 30, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F17", COB_SET_FLD (f0, 2, b_38 + 32, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F18", COB_SET_FLD (f0, 2, b_38 + 34, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F19", COB_SET_FLD (f0, 2, b_38 + 36, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F20", COB_SET_FLD (f0, 2, b_38 + 38, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F21", COB_SET_FLD (f0, 2, b_38 + 40, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F22", COB_SET_FLD (f0, 2, b_38 + 42, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F23", COB_SET_FLD (f0, 2, b_38 + 44, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F24", COB_SET_FLD (f0, 2, b_38 + 46, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F25", COB_SET_FLD (f0, 2, b_38 + 48, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F26", COB_SET_FLD (f0, 2, b_38 + 50, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F27", COB_SET_FLD (f0, 2, b_38 + 52, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F28", COB_SET_FLD (f0, 2, b_38 + 54, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F29", COB_SET_FLD (f0, 2, b_38 + 56, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F30", COB_SET_FLD (f0, 2, b_38 + 58, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F31", COB_SET_FLD (f0, 2, b_38 + 60, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F32", COB_SET_FLD (f0, 2, b_38 + 62, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F33", COB_SET_FLD (f0, 2, b_38 + 64, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F34", COB_SET_FLD (f0, 2, b_38 + 66, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F35", COB_SET_FLD (f0, 2, b_38 + 68, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F36", COB_SET_FLD (f0, 2, b_38 + 70, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F37", COB_SET_FLD (f0, 2, b_38 + 72, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F38", COB_SET_FLD (f0, 2, b_38 + 74, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F39", COB_SET_FLD (f0, 2, b_38 + 76, &a_10), 0, 0);
  cob_dump_field_ext ( 5, "WS-F40", &f_78, 0, 0);
  cob_dump_field_ext ( 1, "WS-BIG", COB_SET_FLD (f0, 2000, b_79, &a_6), 0, 0);
  {
    int i_1;
    int max_1 = 500;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "WS-LINE", &f_80, 0, 1, i_1, 4UL); /* OCCURS 1 500 */
    }
  }

  /* Dump LOCAL-STORAGE SECTION */
  cob_dump_output ("LOCAL-STORAGE");
  cob_dump_field_ext ( 1, "LS-A", COB_SET_FLD (f0, 4, cob_local_ptr, &a_5), 0, 0);
  cob_dump_field_ext ( 1, "LS-G", COB_SET_FLD (f0, (5+3*cob_get_numdisp (cob_local_ptr + 16 + 4, 1)), cob_local_ptr + 16, &a_6), 0, 0);
  cob_dump_field_ext ( 5, "LS-G1", &f_83, 0, 0);
  cob_dump_field_ext ( 5, "LS-G2", &f_84, 0, 0);
  cob_dump_field_ext ( 5, "LS-COUNT", &f_85, 0, 0);
  {
    int i_1;
    int max_1 = cob_get_numdisp (cob_local_ptr + 16 + 4, 1);
    if (max_1 > 3) max_1 = 3;
    for (i_1=0; i_1 < max_1; i_1++)
    {
      cob_dump_field_ext ( 5, "LS-TBL", &f_86, 0, 1, i_1, 3UL); /* OCCURS 1 3 */
    }
  }

  cob_dump_output ("END OF DUMP - shapes");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  if (h_REC_FILE->open_mode != COB_OPEN_CLOSED)
  	cob_close (h_REC_FILE, NULL, COB_CLOSE_NORMAL, 1);
  cob_file_free (&h_REC_FILE,NULL);
  if (b_37) {
  	cob_free_alloc (&b_37, NULL);
  }
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'shapes' */

/* Initialize module structure for shapes */
static void shapes_module_init (cob_module *module)
{
  module->module_name = "shapes";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())shapes;
  module->module_cancel.funcptr = (void *(*)())shapes_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

