/* Generated by           cobc 3.2.0 */
/* Generated from         C:/work/cobol/examples/shapes.cob */
/* Generated at           Sep 19 2026 15:47:09 */
/* GnuCOBOL build date    Jul 31 2026 17:17:58 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc.exe -C -g -fdump=ALL -t C:/work/cobol/build/shapes-paged.lst -ftsymbols -std=ibm C:/work/cobol/examples/shapes.cob */

/* Program local variables for 'shapes' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* EXTERNAL items */
static unsigned char	*b_36 = NULL;  /* WS-EXT */


/* File REC-FILE */
static cob_file		*h_REC_FILE = NULL;
static unsigned char	h_REC_FILE_status[4];

/* BASED WORKING-STORAGE SECTION */
static unsigned char	*b_37 = NULL; /* WS-BASED */


/* LINKAGE SECTION (Items not referenced by USING clause) */
static unsigned char	*b_9 = NULL;  /* XML-NAMESPACE */
static unsigned char	*b_10 = NULL;  /* XML-NAMESPACE-PREFIX */
static unsigned char	*b_11 = NULL;  /* XML-NNAMESPACE */
static unsigned char	*b_12 = NULL;  /* XML-NNAMESPACE-PREFIX */
static unsigned char	*b_13 = NULL;  /* XML-NTEXT */
static unsigned char	*b_14 = NULL;  /* XML-TEXT */


/* Local cob_field items */
cob_field		f0;
cob_field		f1;
cob_field		f2;


/* LOCAL storage pointer */
unsigned char		*cob_local_ptr = NULL;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame_ext	*temp_index;
struct cob_frame_ext	*frame_overflow;
struct cob_frame_ext	*frame_ptr;
struct cob_frame_ext	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_24[24] __attribute__((aligned));	/* REC-FILE Record */
static cob_u8_t	b_25[30] __attribute__((aligned));	/* WS-TABLE */
static int	b_27;	/* WS-IX */
static cob_u8_t	b_30[2] __attribute__((aligned));	/* WS-COUNT */
static cob_u8_t	b_31[18] __attribute__((aligned));	/* WS-ODO-TABLE */
static cob_u8_t	b_34[9] __attribute__((aligned));	/* WS-EDITED */
static cob_u8_t	b_35[3] __attribute__((aligned));	/* WS-A-VERY-LONG-DATA-NAME-OF-THIRTY-FIVE */
static cob_u8_t	b_38[80] __attribute__((aligned));	/* WS-FILLER-GROUP */
static cob_u8_t	b_79[2000] __attribute__((aligned));	/* WS-BIG */

/* End of local data storage */


/* Fields (local) */
static cob_field f_18	= {4, b_24, &a_5};	/* REC-A-KEY */
static cob_field f_21	= {4, b_24, &a_5};	/* REC-B-KEY */
static cob_field f_24	= {24, b_24, &a_5};	/* REC-FILE Record */
static cob_field f_26	= {6, b_25, &a_6};	/* WS-ENTRY */
static cob_field f_27	= {4, (cob_u8_t *)&b_27, &a_9};	/* WS-IX */
static cob_field f_28	= {4, b_25, &a_3};	/* WS-AMOUNT */
static cob_field f_29	= {2, b_25 + 4, &a_5};	/* WS-CODE */
static cob_field f_30	= {2, b_30, &a_10};	/* WS-COUNT */
static cob_field f_33	= {2, b_31, &a_5};	/* WS-COL */
static cob_field f_34	= {9, b_34, &a_4};	/* WS-EDITED */
static cob_field f_36	= {10, NULL, &a_5};	/* WS-EXT */
static cob_field f_37	= {4, NULL, &a_5};	/* WS-BASED */
static cob_field f_78	= {2, b_38 + 78, &a_10};	/* WS-F40 */
static cob_field f_80	= {4, b_79, &a_5};	/* WS-LINE */
static cob_field f_83	= {2, NULL, &a_5};	/* LS-G1 */
static cob_field f_84	= {2, NULL, &a_5};	/* LS-G2 */
static cob_field f_85	= {1, NULL, &a_11};	/* LS-COUNT */
static cob_field f_86	= {3, NULL, &a_5};	/* LS-TBL */

/* End of fields */

