/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/copybook/main.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -I /work/cobol/examples/copybook -A -O0 -gdwarf-4 -o /work/cobol/build/copybook/cpymain -g -fdump=ALL --save-temps -t /work/cobol/build/copybook/copybook.lst -ftsymbols /work/cobol/examples/copybook/main.cob */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"/work/cobol/examples/copybook/main.cob"
#define  COB_PACKAGE_VERSION		"3.1.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Sep 19 2026 14:46:09"
#define  COB_MODULE_DATE		20260919
#define  COB_MODULE_TIME		144609

/* Global variables */
#include "main.c.h"

/* Function prototypes */

static int		CPYMAIN ();
static int		CPYMAIN_ (const int);
static void		CPYMAIN_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (CPYMAIN ());
}

/* Functions */

/* PROGRAM-ID 'CPYMAIN' */

/* ENTRY 'CPYMAIN' */

static int
CPYMAIN ()
{
  return CPYMAIN_ (0);
}

static int
CPYMAIN_ (const int entry)
{
  /* Program local variables */
  #include "main.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     CPYMAIN                 : /work/cobol/examples/copybook/main.cob */
  l_2:;
#line 7 "/work/cobol/examples/copybook/main.cob"
  ENTRY_CPYMAIN:;
#line 104 "main.c"
#line 8 "/work/cobol/examples/copybook/main.cob"
  SECTION_MAIN_20SECTION:;
#line 107 "main.c"

  /* Line: 8         : Paragraph 0000-MAIN               : /work/cobol/examples/copybook/main.cob */
#line 8 "/work/cobol/examples/copybook/main.cob"
  cob_nop ();
#line 112 "main.c"

  /* Line: 9         : PERFORM            : /work/cobol/examples/copybook/main.cob */
  module->module_stmt = 0x00100009;
#line 9 "/work/cobol/examples/copybook/main.cob"
  cob_trace_stmt (st_1);
#line 118 "main.c"
  /* PERFORM 9000-FROM-COPYBOOK */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_6;
  goto l_5;
  l_6:
  frame_ptr--;

  /* Line: 10        : MOVE               : /work/cobol/examples/copybook/main.cob */
  module->module_stmt = 0x0010000A;
#line 10 "/work/cobol/examples/copybook/main.cob"
  cob_trace_stmt (st_2);
#line 133 "main.c"
  *(b_12) = 89;

  /* Line: 11        : DISPLAY            : /work/cobol/examples/copybook/main.cob */
  module->module_stmt = 0x0010000B;
#line 11 "/work/cobol/examples/copybook/main.cob"
  cob_trace_stmt (st_3);
#line 140 "main.c"
  cob_display (0, 1, 2, &c_1, &f_11);

  /* Line: 12        : STOP RUN           : /work/cobol/examples/copybook/main.cob */
  module->module_stmt = 0x0010000C;
#line 12 "/work/cobol/examples/copybook/main.cob"
  cob_trace_stmt (st_4);
#line 147 "main.c"
  cob_stop_run (b_2);

  /* Line: 1         : Paragraph 9000-FROM-COPYBOOK      : /work/cobol/examples/copybook/procpara.cpy */
  l_5:;
#line 1 "/work/cobol/examples/copybook/procpara.cpy"
  cob_nop ();
#line 154 "main.c"

  /* Line: 2         : COMPUTE            : /work/cobol/examples/copybook/procpara.cpy */
  module->module_stmt = 0x00200002;
#line 2 "/work/cobol/examples/copybook/procpara.cpy"
  cob_trace_stmt (st_5);
#line 160 "main.c"
  cob_decimal_set_field (d0, &f_11);
  cob_decimal_set_field (d1, &f_10);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_11, 0);

  /* Line: 3         : DISPLAY            : /work/cobol/examples/copybook/procpara.cpy */
  module->module_stmt = 0x00200003;
#line 3 "/work/cobol/examples/copybook/procpara.cpy"
  cob_trace_stmt (st_3);
#line 170 "main.c"
  cob_display (0, 1, 1, &c_2);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  module->module_stmt = 0x0010000E;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  CPYMAIN_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memcpy (b_8, "CPY", 3);
  cob_set_packed_int (&f_10, 12);
  memcpy (b_8 + 6, "0001999", 7);
  *(cob_u8_ptr)(b_12) = 78;

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  {
    cob_field f0;
    memset(&f0,0,sizeof(f0));
    /* Dump WORKING-STORAGE */
    cob_dump_output("WORKING-STORAGE");
    cob_dump_field_ext ( 1, "CP-REC", COB_SET_FLD(f0, 13, b_8, &a_4), 0, 0);
    cob_dump_field_ext ( 5, "CP-CODE", COB_SET_FLD(f0, 3, b_8, &a_5), 0, 0);
    cob_dump_field_ext ( 5, "CP-QTY", &f_10, 0, 0);
    cob_dump_field_ext ( 5, "CP-PRICE", &f_11, 0, 0);
    cob_dump_field_ext ( 1, "WS-DONE", &f_12, 0, 0);

  }
  cob_dump_output("END OF DUMP - CPYMAIN");
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'CPYMAIN' */

/* Initialize module structure for CPYMAIN */
static void CPYMAIN_module_init (cob_module *module)
{
  module->module_name = "CPYMAIN";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())CPYMAIN;
  module->module_cancel.funcptr = (void *(*)())CPYMAIN_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 1;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

