/* Generated by           cobc 3.1.2.0 */
/* Generated from         /work/cobol/examples/copybook/main.cob */
/* Generated at           Sep 19 2026 14:46:09 */
/* GnuCOBOL build date    Apr 14 2024 07:59:15 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -x -I /work/cobol/examples/copybook -A -O0 -gdwarf-4 -o /work/cobol/build/copybook/cpymain -g -fdump=ALL --save-temps -t /work/cobol/build/copybook/copybook.lst -ftsymbols /work/cobol/examples/copybook/main.cob */

/* Program local variables for 'CPYMAIN' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[13] __attribute__((aligned));	/* CP-REC */
static cob_u8_t	b_12[1] __attribute__((aligned));	/* WS-DONE */

/* End of local data storage */


/* Fields (local) */
static cob_field f_10	= {3, b_8 + 3, &a_3};	/* CP-QTY */
static cob_field f_11	= {7, b_8 + 6, &a_2};	/* CP-PRICE */
static cob_field f_12	= {1, b_12, &a_5};	/* WS-DONE */

/* End of fields */

